Armory Stat Tweaks
╔════════════════════════════╤════════════════════════════╤════════════════════════════╤════════════════════════════╤════════════════════════════╤════════════════════════════╤════════════════════════════╗
║ Total Power                │ CoreDurability             │ Defense                    │ Modifier                   │ PlatesDurability           │ Toughness                  │ ExtraDurability            ║
║                            │ sqrt((n+10)*10)-10         │ n*0.5                      │ sqrt((n+1)*10)-3           │ n*0.3                      │ pow(n+2,2)-4               │ n*0.5                      ║
╟────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────╢
║   -15 paper                │     0 paper                │  0.34 ma.prosperity        │   0.1 paper                │   -21 ardite               │     0 aluminium            │     0 chocolate            ║
║    -9 chocolate            │     1 chocolate            │  0.38 paper                │   0.3 heavy                │   -21 firewood             │     0 amber                │     0 nagascale            ║
║    -7 polyethylene         │     1 ma.prosperity        │  0.75 sponge               │   0.5 knightslime          │   -21 magmaslime           │     0 apatite              │   0.4 heavy                ║
║    -7 wood                 │     1 treatedwood          │   0.9 chocolate            │   0.5 polyethylene         │   -17 netherrack           │     0 aquamarine           │     1 aluminium            ║
║    -6 apatite              │     1 universal_metal      │  1.35 blueslime            │   0.5 rubber               │   -17 prismarine           │     0 cactus               │     1 constantan           ║
║    -6 ma.prosperity        │     1 xu_magical_wood      │   1.5 slime                │   0.5 stone                │   -14 obsidian             │     0 certus_quartz        │     1 construction_alloy   ║
║    -5 flint                │   1.5 meat_metal           │  2.25 livingwood           │   0.6 flint                │    -9 flint                │     0 cheese               │     1 draconium            ║
║    -5 stone                │     2 apatite              │  2.25 wood                 │   0.6 fluxed_electrum      │    -5 blueslime            │     0 chocolate            │     1 fluix_steel          ║
║    -5 void_crystal         │     2 construction_alloy   │   2.5 heavy                │   0.6 prismarine           │    -5 lead                 │     0 cobalt               │     1 invar                ║
║    -4 netherrack           │     2 polyethylene         │     3 bone                 │  0.63 chitinbrowndeathworm │    -5 stone                │     0 conductive_iron      │     1 livingwood           ║
║    -3 construction_alloy   │     2 wood                 │     3 pink_slime           │  0.63 chitintandeathworm   │    -2 electrum             │     0 constantan           │     1 paper                ║
║    -2 heavy                │     3 electrum             │  3.38 construction_alloy   │  0.63 chitinwhitedeathworm │     0 chocolate            │     0 construction_alloy   │     1 primal_metal         ║
║    -2 sky_stone            │     3 mica                 │  3.38 flint                │  0.65 chocolate            │     0 endstone             │     0 copper               │     1 sky_stone            ║
║    -2 tin                  │     3 primal_metal         │  3.38 soularium            │   0.7 lead                 │     0 essence_metal        │     0 desert_myrmex        │     1 steel                ║
║    -1 electrum             │     3 void_crystal         │  3.56 apatite              │   0.7 slime                │     0 iridium              │     0 dragonbone           │     1 stone                ║
║    -1 palis_crystal        │     3 xu_demonic_metal     │  3.75 polyethylene         │  0.75 boron_nitride        │     0 livingrock           │     0 dragonsteel_fire     │     1 tin                  ║
║    -1 restonia_crystal     │     4 conductive_iron      │  3.75 stone                │  0.75 certus_quartz        │     0 lumium               │     0 dragonsteel_ice      │     1 wood                 ║
║    -1 rubber               │     4 dreamwood            │  3.98 netherrack           │  0.75 livingwood           │     0 meat_metal           │     0 dreamwood            │     2 apatite              ║
║     0 aluminium            │     4 refined_glowstone    │  4.22 conductive_iron      │  0.75 nickel               │     0 nagascale            │     0 electrical_steel     │     2 black_quartz         ║
║     0 treatedwood          │     5 aquamarine           │  4.88 dreamwood            │  0.75 restonia_crystal     │     0 palis_crystal        │     0 electrum             │     2 chitinbrowndeathworm ║
║     1 aquamarine           │     5 erodium              │  4.88 sky_stone            │  0.75 sentient_metal       │     0 paper                │     0 elementium           │     2 chitintandeathworm   ║
║     1 bone                 │     5 litherite            │  5.06 redstone_alloy       │  0.75 thorium              │     0 pigiron              │     0 end_steel            │     2 chitinwhitedeathworm ║
║     1 cactus               │     5 palis_crystal        │  5.25 rubber               │  0.78 carbon_fiber         │     0 pink_slime           │     0 energetic_alloy      │     2 dreamwood            ║
║     1 livingwood           │     5 redstone_alloy       │  5.25 void_crystal         │   0.8 apatite              │     0 primal_metal         │     0 energetic_metal      │     2 enderium             ║
║     1 xu_magical_wood      │     5 restonia_crystal     │  5.63 meat_metal           │   0.8 aquamarine           │     0 signalum             │     0 enori_crystal        │     2 endstone             ║
║     2 black_quartz         │     6 kyronite             │     6 copper               │   0.8 black_quartz         │     0 slime                │     0 erodium              │     2 essence_metal        ║
║     2 constantan           │     6 tin                  │  6.08 electrum             │   0.8 energetic_metal      │     0 universal_metal      │     0 essence_metal        │     2 flint                ║
║     2 copper               │     7 magnesium            │  6.75 cheese               │   0.8 mica                 │     0 void_crystal         │     0 fierymetal           │     2 leatherforesttroll   ║
║     2 dreamwood            │     7 pladium              │  6.75 endstone             │   0.8 osmium               │     0 void_metal           │     0 fluix                │     2 leatherfrosttroll    ║
║     2 endstone             │     7 sky_stone            │  6.75 pulsating_iron       │   0.8 platinum             │     1 aluminium            │     0 heavy                │     2 leathermountaintroll ║
║     2 firewood             │     7 stone                │  6.75 tin                  │   0.8 refined_glowstone    │     1 cactus               │     0 iron                 │     2 livingrock           ║
║     2 magnesium            │     8 aethium              │  6.75 treatedwood          │   0.8 tin                  │     1 constantan           │     0 jungle_myrmex        │     2 ma.prosperity        ║
║     3 certus_quartz        │     8 black_quartz         │  6.75 xu_magical_wood      │   0.8 uranium              │     1 construction_alloy   │     0 knightmetal          │     2 malachite_gem        ║
║     3 essence_metal        │     8 certus_quartz        │   7.2 carbon_fiber         │   0.8 void_crystal         │     1 draconium            │     0 litherite            │     2 mica                 ║
║     3 litherite            │     8 enori_crystal        │   7.5 aluminium            │  0.85 boron                │     1 elementium           │     0 livingwood           │     2 nickel               ║
║     3 nickel               │     8 flint                │   7.5 cactus               │  0.85 cactus               │     1 enderium             │     0 ma.base_essence      │     2 platinum             ║
║     3 universal_metal      │     8 fluix                │   7.5 palis_crystal        │  0.85 endstone             │     1 invar                │     0 ma.prosperity        │     2 polyethylene         ║
║     3 uranium              │     8 ionite               │   7.5 restonia_crystal     │  0.85 iron                 │     1 livingwood           │     0 ma.soulium           │     2 psigem               ║
║     4 erodium              │     8 obsidian             │  7.59 electrical_steel     │  0.85 magmaslime           │     1 polyethylene         │     0 malachite_gem        │     2 psimetal             ║
║     4 fluix                │     8 rubber               │   7.8 livingrock           │  0.85 manasteel            │     1 sky_stone            │     0 manasteel            │     2 rubber               ║
║     4 iron                 │     8 starmetal            │  8.25 lead                 │  0.85 netherrack           │     1 tin                  │     0 mica                 │     2 tanzanite            ║
║     4 mica                 │     8 thorium              │     9 bronze               │   0.9 aluminium            │     1 wood                 │     0 mirion               │     2 treatedwood          ║
║     4 primal_metal         │     8 uranium              │     9 constantan           │   0.9 cobalt               │     2 apatite              │     0 nagascale            │     2 void_crystal         ║
║     4 prismarine           │     8 vibrant_alloy        │  9.38 aquamarine           │   0.9 fluix_steel          │     2 copper               │     0 netherrack           │     2 xu_demonic_metal     ║
║     4 refined_glowstone    │     8 void_metal           │  9.38 magnesium            │   0.9 lonsdaleite          │     2 crystal_matrix       │     0 nickel               │     2 xu_magical_wood      ║
║     4 thorium              │     9 aluminium            │  9.75 ardite               │   0.9 obsidian             │     2 dreamwood            │     0 osgloglas            │     3 cactus               ║
║     5 blueslime            │     9 bone                 │  9.75 black_quartz         │   0.9 steel                │     2 malachite_gem        │     0 palis_crystal        │     3 calebronzeseaserpent ║
║     5 lead                 │     9 copper               │  9.75 essence_metal        │  0.95 silver               │     2 mica                 │     0 paper                │     3 calepurpleseaserpent ║
║     5 manasteel            │     9 iron                 │ 10.35 refined_obsidian     │     1 advanced_alloy       │     2 nickel               │     0 plague_metal         │     3 certus_quartz        ║
║     6 kyronite             │     9 livingwood           │  10.5 calebronzeseaserpent │     1 aethium              │     2 platinum             │     0 psigem               │     3 iron                 ║
║     6 magmaslime           │     9 ma.base_essence      │  10.5 calepurpleseaserpent │     1 alumite              │     2 psigem               │     0 psimetal             │     3 ledeepblueseaserpent ║
║     6 obsidian             │     9 steeleaf             │  10.5 chitinbrowndeathworm │     1 bound_metal          │     2 psimetal             │     0 pulsating_iron       │     3 manasteel            ║
║     7 bronze               │    10 cactus               │  10.5 chitintandeathworm   │     1 emerald_plustic      │     2 tanzanite            │     0 redstone_alloy       │     3 manyullyn            ║
║     7 elementium           │    10 constantan           │  10.5 chitinwhitedeathworm │     1 enori_crystal        │     2 treatedwood          │     0 restonia_crystal     │     3 palis_crystal        ║
║     7 enori_crystal        │    10 heavy                │  10.5 leatherforesttroll   │     1 erodium              │     2 xu_demonic_metal     │     0 rubber               │     3 scaleblueseaserpent  ║
║     7 invar                │    10 manasteel            │  10.5 leatherfrosttroll    │     1 firewood             │     2 xu_magical_wood      │     0 soularium            │     3 scalegreenseaserpent ║
║     7 sentient_metal       │    10 sentient_metal       │  10.5 leathermountaintroll │     1 fluix                │     3 aquamarine           │     0 steeleaf             │     3 scaleredseaserpent   ║
║     7 slime                │    10 silver               │  10.5 ledeepblueseaserpent │     1 flux_crystal         │     3 black_quartz         │     0 stone                │     3 scaletealseaserpent  ║
║     7 void_metal           │    11 alumite              │  10.5 nickel               │     1 hard_carbon          │     3 bone                 │     0 tanzanite            │  3.96 iridium              ║
║     8 chitinbrowndeathworm │    11 bound_metal          │  10.5 osmium               │     1 infinity_metal       │     3 carbon_fiber         │     0 thaumium             │     4 aquamarine           ║
║     8 chitintandeathworm   │    11 cheese               │  10.5 scaleblueseaserpent  │     1 ionite               │     3 fluix                │     0 tin                  │     4 bone                 ║
║     8 chitinwhitedeathworm │    11 chitinbrowndeathworm │  10.5 scalegreenseaserpent │     1 kyronite             │     3 litherite            │     0 titanium             │     4 fluix                ║
║     8 draconium            │    11 chitintandeathworm   │  10.5 scaleredseaserpent   │     1 litherite            │     3 magnesium            │     0 topaz                │     4 litherite            ║
║     8 osmium               │    11 chitinwhitedeathworm │  10.5 scaletealseaserpent  │     1 magnesium            │     3 refined_obsidian     │     0 treatedwood          │     4 ma.soulium           ║
║     8 pigiron              │    11 dragonbone           │ 10.88 uranium              │     1 manyullyn            │     3 restonia_crystal     │     0 universal_metal      │     4 magnesium            ║
║     9 fluix_steel          │    11 electrical_steel     │ 11.25 certus_quartz        │     1 neutronium           │     3 rubber               │     0 vibrant_alloy        │     4 restonia_crystal     ║
║     9 pladium              │    11 essence_metal        │ 11.25 elementium           │     1 peridot              │     3 silver               │     0 void_crystal         │     4 scalebluedragon      ║
║    10 energetic_metal      │    11 fluix_steel          │ 11.25 enori_crystal        │     1 pink_metal           │     3 thorium              │     0 weezer               │     4 scalebronzedragon    ║
║    10 silver               │    11 flux_crystal         │ 11.25 iron                 │     1 pladium              │     3 uranium              │     0 wood                 │     4 scalegraydragon      ║
║    11 cobalt               │    11 ma.soulium           │ 11.25 manasteel            │     1 primal_metal         │     3 wyvern_metal         │     0 xu_demonic_metal     │     4 scalegreendragon     ║
║    11 leatherforesttroll   │    11 netherrack           │ 11.63 fluix                │     1 ruby                 │     4 boron                │     0 xu_enchanted_metal   │     4 scalereddragon       ║
║    11 leatherfrosttroll    │    11 nickel               │ 11.63 thorium              │     1 sapphire             │     4 erodium              │     0 xu_evil_metal        │     4 scalesapphiredragon  ║
║    11 leathermountaintroll │    11 peridot              │  11.7 cobalt               │     1 sky_stone            │     4 iron                 │     0 xu_magical_wood      │     4 scalesilverdragon    ║
║    11 redstone_alloy       │    11 pigiron              │ 11.81 xu_enchanted_metal   │     1 terrasteel           │     4 kyronite             │  0.15 magnesium            │     4 scalewhitedragon     ║
║    12 alumite              │    11 ruby                 │    12 invar                │     1 wood                 │     4 ma.soulium           │  0.25 amethyst             │     4 thorium              ║
║    12 electrical_steel     │    11 sapphire             │    12 sentient_metal       │  1.05 copper               │     5 aethium              │  0.25 livingrock           │     4 uranium              ║
║    12 knightslime          │    12 boron                │    12 signalum             │   1.1 bone                 │     5 alumite              │  0.25 meat_metal           │   4.8 carbon_fiber         ║
║    12 peridot              │    12 bronze               │ 12.15 obsidian             │   1.1 bronze               │     5 bronze               │  0.38 firewood             │     5 boron                ║
║    12 pink_slime           │    12 draconium            │ 12.53 pigiron              │   1.1 constantan           │     5 certus_quartz        │  0.38 osmium               │     5 boron_nitride        ║
║    12 ruby                 │    12 endstone             │ 12.75 litherite            │   1.1 draconium            │     5 energetic_metal      │  0.38 polyethylene         │     5 bronze               ║
║    12 sapphire             │    12 energetic_metal      │ 12.75 lumium               │   1.1 electrum             │     5 heavy                │  0.53 uranium              │     5 elementium           ║
║    13 ardite               │    12 lead                 │ 12.75 silver               │   1.1 palis_crystal        │     5 ionite               │  0.75 black_quartz         │     5 erodium              ║
║    13 livingrock           │    12 prismarine           │ 12.83 knightslime          │   1.1 tough                │     5 ma.base_essence      │  0.75 bone                 │     5 hard_carbon          ║
║    14 platinum             │    12 signalum             │ 13.13 firewood             │  1.15 iridium              │     5 osmium               │  0.75 draconium            │     5 ionite               ║
║    15 boron                │  12.6 carbon_fiber         │  13.5 fluix_steel          │   1.2 elementium           │     5 peridot              │  0.75 endstone             │     5 kyronite             ║
║    15 ionite               │ 12.98 tough                │  13.5 flux_crystal         │   1.2 pigiron              │     5 pladium              │  0.75 flint                │     5 ma.base_essence      ║
║    16 conductive_iron      │    13 firewood             │  13.5 refined_glowstone    │   1.2 sponge               │     5 refined_glowstone    │  0.75 invar                │     5 netherrack           ║
║    16 diamantine_crystal   │    13 ma.inferium          │  13.5 scalebluedragon      │  1.25 diamantine_crystal   │     5 ruby                 │  0.75 knightslime          │     5 obsidian             ║
║    16 emerald_plustic      │    13 steel                │  13.5 scalebronzedragon    │  1.25 dreamwood            │     5 sapphire             │  0.75 kyronite             │     5 pink_metal           ║
║    16 fluxed_electrum      │    13 xu_enchanted_metal   │  13.5 scalegraydragon      │  1.25 emeraldic_crystal    │     5 sentient_metal       │  0.75 lonsdaleite          │     5 pladium              ║
║    16 manyullyn            │    14 diamantine_crystal   │  13.5 scalegreendragon     │  1.25 enderium             │     5 topaz                │  0.75 pigiron              │     5 refined_glowstone    ║
║    17 cheese               │    14 elementium           │  13.5 scalereddragon       │  1.25 invar                │     5 vibrant_alloy        │  0.75 sentient_metal       │     5 terrasteel           ║
║    17 lonsdaleite          │    14 emerald_plustic      │  13.5 scalesapphiredragon  │  1.25 leatherforesttroll   │     5 xu_evil_metal        │  0.75 sky_stone            │     5 topaz                ║
║    17 refined_obsidian     │    14 fluxed_electrum      │  13.5 scalesilverdragon    │  1.25 leatherfrosttroll    │     6 boron_nitride        │  0.75 void_metal           │     5 vibrant_alloy        ║
║    18 advanced_alloy       │    14 livingrock           │  13.5 scalewhitedragon     │  1.25 leathermountaintroll │     6 bound_metal          │  0.83 thorium              │     5 void_metal           ║
║    18 ma.base_essence      │    14 magmaslime           │  13.5 universal_metal      │  1.25 pink_slime           │     6 cobalt               │   0.9 boron                │     5 xu_evil_metal        ║
║    18 meat_metal           │    14 osmium               │ 13.52 starmetal            │  1.25 refined_obsidian     │     6 electrical_steel     │  0.94 bronze               │     6 aethium              ║
║    18 xu_enchanted_metal   │ 14.04 hard_carbon          │  13.8 steel                │   1.3 blueslime            │     6 enori_crystal        │     1 lumium               │     6 copper               ║
║    19 bound_metal          │    15 blueslime            │ 13.88 erodium              │   1.4 ardite               │     6 fluix_steel          │     1 ma.inferium          │     6 crystal_matrix       ║
║    19 flux_crystal         │    15 cobalt               │  14.1 prismarine           │   1.4 signalum             │     6 manasteel            │     1 signalum             │     6 electrical_steel     ║
║    19 ma.soulium           │    15 desert_myrmex        │ 14.55 magmaslime           │  1.45 ma.prosperity        │     6 pink_metal           │  1.13 hard_carbon          │     6 lead                 ║
║    19 steel                │    15 jungle_myrmex        │ 14.61 ma.base_essence      │   1.5 crystal_matrix       │     6 tough                │  1.13 leatherforesttroll   │     6 osmium               ║
║    19 xu_demonic_metal     │    15 knightslime          │    15 alumite              │   1.5 essence_metal        │     7 draconic_metal       │  1.13 leatherfrosttroll    │     6 prismarine           ║
║    20 pink_metal           │    15 leatherforesttroll   │    15 bound_metal          │   1.5 livingrock           │     7 emerald_plustic      │  1.13 leathermountaintroll │     6 sentient_metal       ║
║    21 emeraldic_crystal    │    15 leatherfrosttroll    │    15 emerald_plustic      │   1.5 wyvern_metal         │     7 flux_crystal         │  1.13 refined_glowstone    │     6 tough                ║
║    21 enderium             │    15 leathermountaintroll │    15 energetic_metal      │   1.6 lumium               │     7 hard_carbon          │   1.5 advanced_alloy       │     6 wyvern_metal         ║
║    22 sponge               │    15 manyullyn            │    15 kyronite             │   1.8 draconic_metal       │     7 ma.prosperity        │   1.5 diamantine_crystal   │     7 bound_metal          ║
║    23 psigem               │ 15.99 thaumium             │    15 lonsdaleite          │   1.8 void_metal           │     7 osmiridium           │   1.5 fluxed_electrum      │     7 knightslime          ║
║    23 psimetal             │    16 ardite               │    15 manyullyn            │  1.88 scalebluedragon      │     7 xu_enchanted_metal   │   1.5 lead                 │     7 osmiridium           ║
║    24 nagascale            │    16 emeraldic_crystal    │    15 peridot              │  1.88 scalebronzedragon    │     8 advanced_alloy       │   1.5 ma.prudentium        │     7 xu_enchanted_metal   ║
║    25 calebronzeseaserpent │    16 invar                │    15 ruby                 │  1.88 scalegraydragon      │     8 amber                │   1.5 pladium              │     8 alumite              ║
║    25 calepurpleseaserpent │    16 lonsdaleite          │    15 sapphire             │  1.88 scalegreendragon     │     8 diamantine_crystal   │   1.5 platinum             │     8 amber                ║
║    25 ledeepblueseaserpent │    16 lumium               │    15 thaumium             │  1.88 scalereddragon       │     8 mirion               │   1.5 prismarine           │     8 energetic_metal      ║
║    25 scaleblueseaserpent  │    16 slime                │    15 void_metal           │  1.88 scalesapphiredragon  │     8 osgloglas            │   1.5 silver               │     8 enori_crystal        ║
║    25 scalegreenseaserpent │    16 sponge               │ 15.19 ma.inferium          │  1.88 scalesilverdragon    │     8 starmetal            │   1.5 slime                │     8 firewood             ║
║    25 scaleredseaserpent   │    16 wyvern_metal         │ 15.53 ma.soulium           │  1.88 scalewhitedragon     │     8 steel                │  1.65 alumite              │     8 magmaslime           ║
║    25 scaletealseaserpent  │    17 pink_slime           │ 15.75 diamantine_crystal   │     2 universal_metal      │     8 terrasteel           │  1.65 emerald_plustic      │     8 mirion               ║
║    26 aethium              │  17.4 refined_obsidian     │ 15.75 platinum             │   2.2 chaotic_metal        │     9 fluxed_electrum      │  1.65 peridot              │     8 osgloglas            ║
║    26 hard_carbon          │    18 advanced_alloy       │ 15.75 terrasteel           │  3.13 calebronzeseaserpent │     9 thaumium             │  1.65 ruby                 │     8 peridot              ║
║    26 scalebluedragon      │  18.9 iridium              │ 16.13 crystal_matrix       │  3.13 calepurpleseaserpent │     9 titanium             │  1.65 sapphire             │     8 pigiron              ║
║    26 scalebronzedragon    │    19 crystal_matrix       │ 16.13 pladium              │  3.13 ledeepblueseaserpent │    10 emeraldic_crystal    │  1.69 blueslime            │     8 refined_obsidian     ║
║    26 scalegraydragon      │    21 dark_steel           │  16.5 advanced_alloy       │  3.13 scaleblueseaserpent  │    10 manyullyn            │  1.69 chitinbrowndeathworm │     8 ruby                 ║
║    26 scalegreendragon     │    21 terrasteel           │  16.5 fluxed_electrum      │  3.13 scalegreenseaserpent │    10 sponge               │  1.69 chitintandeathworm   │     8 sapphire             ║
║    26 scalereddragon       │    23 calebronzeseaserpent │  16.5 pink_metal           │  3.13 scaleredseaserpent   │    10 steeleaf             │  1.69 chitinwhitedeathworm │     8 silver               ║
║    26 scalesapphiredragon  │    23 calepurpleseaserpent │  16.5 primal_metal         │  3.13 scaletealseaserpent  │    11 chitinbrowndeathworm │   1.8 iridium              │     8 starmetal            ║
║    26 scalesilverdragon    │    23 ledeepblueseaserpent │ 16.86 xu_demonic_metal     │   3.5 meat_metal           │    11 chitintandeathworm   │  1.88 fluix_steel          │     9 blueslime            ║
║    26 scalewhitedragon     │    23 nagascale            │ 16.88 emeraldic_crystal    │   4.5 construction_alloy   │    11 chitinwhitedeathworm │  1.88 magmaslime           │     9 flux_crystal         ║
║    27 carbon_fiber         │    23 psigem               │ 16.88 psigem               │   4.5 soularium            │    11 lonsdaleite          │  1.88 primal_metal         │     9 thaumium             ║
║    27 malachite_gem        │    23 psimetal             │ 16.88 psimetal             │  5.63 conductive_iron      │    12 chaotic_metal        │  1.88 refined_obsidian     │     9 titanium             ║
║    28 signalum             │    23 scaleblueseaserpent  │ 16.88 wyvern_metal         │  6.48 treatedwood          │    12 ma.inferium          │     2 ma.intermedium       │    10 diamantine_crystal   ║
║    30 lumium               │    23 scalegreenseaserpent │ 17.25 ionite               │  6.75 redstone_alloy       │    13 amethyst             │  2.03 tough                │    10 electrum             ║
║    30 tanzanite            │    23 scaleredseaserpent   │    18 draconium            │     9 cheese               │    13 cheese               │   2.2 osmiridium           │    10 sponge               ║
║    30 topaz                │    23 scaletealseaserpent  │    18 neutronium           │     9 pulsating_iron       │    13 desert_myrmex        │  2.25 carbon_fiber         │    10 steeleaf             ║
║    31 desert_myrmex        │    24 malachite_gem        │ 18.38 aethium              │     9 xu_magical_wood      │    13 jungle_myrmex        │  2.25 emeraldic_crystal    │    11 advanced_alloy       ║
║    31 jungle_myrmex        │    25 pink_metal           │ 18.38 enderium             │ 10.13 electrical_steel     │    13 knightslime          │  2.25 manyullyn            │    11 cobalt               ║
║    31 pulsating_iron       │    25 tanzanite            │ 18.56 desert_myrmex        │ 15.75 xu_enchanted_metal   │    13 redstone_alloy       │  2.25 pink_metal           │    11 draconic_metal       ║
║    31 vibrant_alloy        │    25 xu_evil_metal        │ 18.56 jungle_myrmex        │    18 starmetal            │    15 leatherforesttroll   │  2.25 pink_slime           │    11 emerald_plustic      ║
║    32 amber                │    26 draconic_metal       │  18.9 energetic_alloy      │ 19.48 ma.base_essence      │    15 leatherfrosttroll    │  2.25 scalebluedragon      │    11 emeraldic_crystal    ║
║    33 steeleaf             │    26 energetic_alloy      │ 19.13 boron                │ 20.25 ma.inferium          │    15 leathermountaintroll │  2.25 scalebronzedragon    │    11 fluxed_electrum      ║
║    33 thaumium             │    26 ma.prudentium        │ 19.24 amber                │  20.7 ma.soulium           │    15 plague_metal         │  2.25 scalegraydragon      │    11 pink_slime           ║
║    33 tough                │    26 platinum             │ 19.35 nagascale            │  22.5 end_steel            │    16 ma.prudentium        │  2.25 scalegreendragon     │    11 slime                ║
║    34 dragonbone           │    26 topaz                │ 20.25 dark_steel           │  22.5 psigem               │    17 dragonbone           │  2.25 scalereddragon       │    11 universal_metal      ║
║    34 iridium              │    27 scalebluedragon      │ 20.25 dragonbone           │  22.5 psimetal             │    21 conductive_iron      │  2.25 scalesapphiredragon  │    12 ardite               ║
║    34 terrasteel           │    27 scalebronzedragon    │ 20.25 hard_carbon          │    23 thaumium             │    21 dark_steel           │  2.25 scalesilverdragon    │    12 ma.inferium          ║
║    35 ma.inferium          │    27 scalegraydragon      │ 20.25 plague_metal         │ 24.75 desert_myrmex        │    21 pulsating_iron       │  2.25 scalewhitedragon     │    13 amethyst             ║
║    36 crystal_matrix       │    27 scalegreendragon     │ 20.25 topaz                │ 24.75 jungle_myrmex        │    22 fierymetal           │   2.5 ma.superium          │    13 cheese               ║
║    39 plague_metal         │    27 scalereddragon       │ 20.59 malachite_gem        │  25.2 energetic_alloy      │    23 calebronzeseaserpent │  2.63 enderium             │    13 desert_myrmex        ║
║    44 xu_evil_metal        │    27 scalesapphiredragon  │ 21.38 tough                │ 25.65 amber                │    23 calepurpleseaserpent │  2.63 ionite               │    13 jungle_myrmex        ║
║    46 titanium             │    27 scalesilverdragon    │ 22.34 ma.prudentium        │  25.8 nagascale            │    23 ledeepblueseaserpent │  2.63 obsidian             │    13 lonsdaleite          ║
║    48 wyvern_metal         │    27 scalewhitedragon     │  22.5 boron_nitride        │    27 dark_steel           │    23 scaleblueseaserpent  │  2.81 calebronzeseaserpent │    13 redstone_alloy       ║
║    51 energetic_alloy      │    28 amber                │  22.5 mica                 │    27 dragonbone           │    23 scalegreenseaserpent │  2.81 calepurpleseaserpent │    15 chaotic_metal        ║
║    52 mirion               │    28 enderium             │ 23.63 tanzanite            │    27 plague_metal         │    23 scaleredseaserpent   │  2.81 ledeepblueseaserpent │    15 plague_metal         ║
║    53 ma.prudentium        │    29 plague_metal         │ 24.91 titanium             │    27 titanium             │    23 scaletealseaserpent  │  2.81 scaleblueseaserpent  │    16 ma.prudentium        ║
║    54 fierymetal           │    30 end_steel            │ 25.92 iridium              │    27 topaz                │    26 end_steel            │  2.81 scalegreenseaserpent │    17 dragonbone           ║
║    54 starmetal            │    32 boron_nitride        │    27 knightmetal          │ 27.45 malachite_gem        │    26 ma.intermedium       │  2.81 scaleredseaserpent   │    20 meat_metal           ║
║    56 end_steel            │    35 pulsating_iron       │    27 steeleaf             │ 29.79 ma.prudentium        │    27 scalebluedragon      │  2.81 scaletealseaserpent  │    21 conductive_iron      ║
║    58 boron_nitride        │    36 fierymetal           │  29.7 fierymetal           │  31.5 tanzanite            │    27 scalebronzedragon    │  2.88 crystal_matrix       │    21 dark_steel           ║
║    60 osgloglas            │    41 chaotic_metal        │ 30.38 mirion               │    36 knightmetal          │    27 scalegraydragon      │     3 ardite               │    21 lumium               ║
║    65 osmiridium           │    46 knightmetal          │ 30.38 vibrant_alloy        │    36 osmiridium           │    27 scalegreendragon     │     3 bound_metal          │    21 pulsating_iron       ║
║    66 dark_steel           │    50 osmiridium           │ 31.15 ma.intermedium       │    36 steeleaf             │    27 scalereddragon       │     3 dark_steel           │    21 signalum             ║
║    70 amethyst             │    53 ma.intermedium       │ 33.75 end_steel            │  39.6 fierymetal           │    27 scalesapphiredragon  │     3 flux_crystal         │    22 fierymetal           ║
║    72 knightmetal          │    57 dragonsteel_fire     │ 33.75 weezer               │ 39.96 xu_demonic_metal     │    27 scalesilverdragon    │     3 ma.supremium         │    26 end_steel            ║
║    78 weezer               │    57 dragonsteel_ice      │ 34.02 osmiridium           │  40.5 mirion               │    27 scalewhitedragon     │  3.38 steel                │    26 ma.intermedium       ║
║    79 ma.intermedium       │    57 weezer               │ 37.13 osgloglas            │  40.5 vibrant_alloy        │    33 energetic_alloy      │   3.5 starmetal            │    33 energetic_alloy      ║
║    82 dragonsteel_fire     │    59 soularium            │  37.5 dragonsteel_fire     │ 41.53 ma.intermedium       │    38 ma.superium          │  3.75 sponge               │    38 ma.superium          ║
║    82 dragonsteel_ice      │    63 titanium             │  37.5 dragonsteel_ice      │    45 weezer               │    41 weezer               │  3.99 boron_nitride        │    41 weezer               ║
║    99 soularium            │    64 amethyst             │  37.5 ma.superium          │  49.5 osgloglas            │    42 dragonsteel_fire     │  4.13 aethium              │    42 dragonsteel_fire     ║
║   105 ma.superium          │    73 mirion               │  37.5 ma.supremium         │    50 dragonsteel_fire     │    42 dragonsteel_ice      │   4.5 terrasteel           │    42 dragonsteel_ice      ║
║   119 ma.supremium         │    90 ma.superium          │  37.5 xu_evil_metal        │    50 dragonsteel_ice      │    44 knightmetal          │     6 wyvern_metal         │    44 knightmetal          ║
║   141 draconic_metal       │    90 ma.supremium         │ 39.38 draconic_metal       │    50 ma.superium          │    50 ma.supremium         │  10.5 draconic_metal       │    50 ma.supremium         ║
║   279 neutronium           │    90 osgloglas            │  41.5 amethyst             │    50 ma.supremium         │    83 neutronium           │ 11.25 neutronium           │    83 neutronium           ║
║   465 chaotic_metal        │   500 infinity_metal       │ 69.75 infinity_metal       │    50 xu_evil_metal        │   104 soularium            │ 20.25 chaotic_metal        │   104 soularium            ║
║  1516 infinity_metal       │   833 neutronium           │    72 chaotic_metal        │  54.5 amethyst             │   500 infinity_metal       │    30 infinity_metal       │   500 infinity_metal       ║
╟────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────╢
║ Total Power                │ CoreDurability             │ Defense                    │ Modifier                   │ PlatesDurability           │ Toughness                  │ ExtraDurability            ║
╚════════════════════════════╧════════════════════════════╧════════════════════════════╧════════════════════════════╧════════════════════════════╧════════════════════════════╧════════════════════════════╝


Arrow Shaft Stat Tweaks
╔════════════════════╤════════════════════╤════════════════════╗
║ Total Power        │ Modifier           │ BonusAmmo          ║
║                    │ n*10.0             │ n*0.2              ║
╟────────────────────┼────────────────────┼────────────────────╢
║     0 heavy        │   0.2 heavy        │   -10 heavy        ║
║     7 endrod       │   0.6 steeleaf     │     0 fierymetal   ║
║     8 fierymetal   │   0.7 endrod       │     0 ice          ║
║     8 steeleaf     │  0.75 polyethylene │     0 livingwood   ║
║     9 blaze        │   0.8 blaze        │     0 tnt          ║
║    10 bone         │   0.8 fierymetal   │     0 treatedwood  ║
║    10 ice          │   0.9 bone         │     0 wood         ║
║    10 livingwood   │  0.95 ice          │     1 endrod       ║
║    10 tnt          │  0.95 tnt          │     2 dragonbone   ║
║    10 wood         │     1 livingwood   │     3 blaze        ║
║    12 treatedwood  │     1 wood         │     5 bone         ║
║    13 dragonbone   │  1.05 reed         │    10 reed         ║
║    13 reed         │   1.2 treatedwood  │    10 steeleaf     ║
║    15 polyethylene │  1.25 dreamwood    │    20 nagascale    ║
║    18 dreamwood    │   1.3 dragonbone   │    25 dreamwood    ║
║    18 nagascale    │   1.4 nagascale    │    38 polyethylene ║
╟────────────────────┼────────────────────┼────────────────────╢
║ Total Power        │ Modifier           │ BonusAmmo          ║
╚════════════════════╧════════════════════╧════════════════════╝


Bowstring Stat Tweaks
╔════════════════════════╤════════════════════════╗
║ Total Power            │ Modifier               ║
║                        │ n*10.0                 ║
╟────────────────────────┼────────────────────────╢
║    10 hemp             │     1 hemp             ║
║    10 slimevine_blue   │     1 slimevine_blue   ║
║    10 slimevine_purple │     1 slimevine_purple ║
║    10 string           │     1 string           ║
║    10 vine             │     1 vine             ║
║    13 mana_string      │  1.25 string_cheese    ║
║    13 string_cheese    │   1.3 mana_string      ║
║    15 soularium        │   1.5 soularium        ║
╟────────────────────────┼────────────────────────╢
║ Total Power            │ Modifier               ║
╚════════════════════════╧════════════════════════╝


Fletching Stat Tweaks
╔══════════════════════════╤══════════════════════════╤══════════════════════════╗
║ Total Power              │ Accuracy                 │ Modifier                 ║
║                          │ n*40.0                   │ n*10.0                   ║
╟──────────────────────────┼──────────────────────────┼──────────────────────────╢
║    35 leaf               │   0.5 leaf               │   0.7 amphithere_feather ║
║    43 amphithere_feather │   0.8 slimeleaf_blue     │   0.8 steeleaf           ║
║    45 slimeleaf_blue     │   0.8 slimeleaf_orange   │     1 feather            ║
║    45 slimeleaf_orange   │   0.8 slimeleaf_purple   │  1.15 raven_feather      ║
║    45 slimeleaf_purple   │   0.9 amphithere_feather │  1.25 slimeleaf_blue     ║
║    48 steeleaf           │  0.95 raven_feather      │  1.25 slimeleaf_orange   ║
║    50 feather            │     1 feather            │  1.25 slimeleaf_purple   ║
║    50 raven_feather      │     1 steeleaf           │   1.5 leaf               ║
║    61 stymph_feather     │   1.1 stymph_feather     │  1.56 titanium           ║
║    64 titanium           │   1.2 titanium           │  1.65 stymph_feather     ║
╟──────────────────────────┼──────────────────────────┼──────────────────────────╢
║ Total Power              │ Accuracy                 │ Modifier                 ║
╚══════════════════════════╧══════════════════════════╧══════════════════════════╝


Stat Tweaks
╔══════════════════════════╤═══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╗
║ Total Power              │ HeadDurability            │ MiningSpeed              │ AttackDamage             │ HarvestLevel             │ HandleModifier           │ HandleDurability         │ ExtraDurability          │ DrawSpeed                │ Range                    │ BonusDamage              ║
║                          │ sqrt(abs(n*10))*sign(n)/3 │ pow(n+1,2)               │ pow(n+1,2)/5             │ n*5                      │ pow(n+3,2)-9             │ log(abs(n)+1)*sign(n)+8  │ log(n+50)*2-4            │ sqrt(n*10)               │ n*4                      │ n*2                      ║
╟──────────────────────────┼───────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────╢
║    16 paper              │     9 paper               │  0.01 heavy              │     0 sponge             │     0 bone               │   0.1 paper              │ -1400 energetic_alloy    │   -40 heavy              │  0.01 heavy              │   0.1 heavy              │    -4 meat_metal         ║
║    23 chocolate          │    13 universal_metal     │  0.38 paper              │  0.04 paper              │     0 cactus             │  0.15 chocolate          │  -350 ardite             │     1 meat_metal         │  0.08 chocolate          │   0.3 chocolate          │    -4 signalum           ║
║    27 stone              │    19 chocolate           │  0.38 xu_demonic_metal   │  0.08 ma.prosperity      │     0 chocolate          │  0.25 xu_demonic_metal   │  -350 firewood           │     4 primal_metal       │   0.1 soularium          │   0.4 endstone           │    -2 paper              ║
║    28 wood               │    26 wood                │  0.62 ma.prosperity      │  0.75 construction_alloy │     0 dreamwood          │   0.4 dragonsteel_fire   │  -350 magmaslime         │     4 void_crystal       │   0.2 endstone           │   0.4 flint              │    -1 endstone           ║
║    31 construction_alloy │    26 xu_magical_wood     │  0.75 plague_metal       │  0.75 soularium          │     0 flint              │   0.4 dragonsteel_ice    │  -262 netherrack         │     5 magnesium          │   0.2 flint              │   0.4 netherrack         │    -1 flint              ║
║    34 flint              │    27 ma.prosperity       │  0.75 soularium          │  0.94 conductive_iron    │     0 paper              │   0.5 construction_alloy │  -262 prismarine         │     6 chocolate          │   0.2 netherrack         │   0.4 obsidian           │    -1 netherrack         ║
║    38 dreamwood          │    38 construction_alloy  │  0.94 construction_alloy │  1.13 redstone_alloy     │     0 pink_slime         │   0.5 heavy              │  -175 obsidian           │     8 black_quartz       │   0.2 obsidian           │   0.4 paper              │    -1 obsidian           ║
║    43 xu_magical_wood    │    38 electrum            │   1.5 chocolate          │  1.13 rubber             │     0 polyethylene       │   0.5 knightslime        │  -131 meat_metal         │     8 construction_alloy │   0.2 prismarine         │   0.4 prismarine         │    -1 prismarine         ║
║    45 cactus             │    60 heavy               │   1.5 wood               │  1.35 blueslime          │     0 soularium          │   0.5 manyullyn          │  -105 flint              │     8 thorium            │   0.2 stone              │   0.4 redstone_alloy     │    -1 stone              ║
║    48 apatite            │    60 xu_demonic_metal    │   1.5 xu_magical_wood    │  1.35 slime              │     0 stone              │   0.5 polyethylene       │   -87 blueslime          │     8 uranium            │   0.2 tanzanite          │   0.4 stone              │    -1 tanzanite          ║
║    48 redstone_alloy     │    76 treatedwood         │  1.58 magmaslime         │   1.5 cheese             │     0 wood               │   0.5 rubber             │   -87 lead               │    11 paper              │  0.25 neutronium         │   0.4 tanzanite          │  -0.5 cheese             ║
║    49 meat_metal         │    80 conductive_iron     │  1.88 energetic_alloy    │   1.5 chocolate          │     1 aluminium          │   0.5 soularium          │   -87 osgloglas          │    11 signalum           │  0.25 pulsating_iron     │   0.5 construction_alloy │     0 aquamarine         ║
║    50 livingrock         │    83 dreamwood           │  1.88 redstone_alloy     │   1.5 pink_slime         │     1 apatite            │   0.5 stone              │   -87 stone              │    11 wood               │   0.3 dark_steel         │   0.5 meat_metal         │     0 black_quartz       ║
║    50 polyethylene       │    90 livingwood          │  2.25 dragonbone         │   1.5 pulsating_iron     │     1 blueslime          │   0.5 vibrant_alloy      │   -87 vibrant_alloy      │    11 xu_magical_wood    │   0.3 end_steel          │   0.5 rubber             │     0 blueslime          ║
║    50 tin                │    90 redstone_alloy      │  2.25 dreamwood          │   1.5 wood               │     1 cheese             │   0.6 flint              │   -52 malachite_gem      │    15 livingwood         │  0.38 boron_nitride      │   0.5 soularium          │     0 bone               ║
║    51 netherrack         │    90 stone               │  2.25 malachite_gem      │   1.5 xu_magical_wood    │     1 construction_alloy │   0.6 fluxed_electrum    │   -52 peridot            │    15 lumium             │  0.38 osmiridium         │   0.6 polyethylene       │     0 cactus             ║
║    53 bone               │   101 meat_metal          │  2.25 tanzanite          │  1.69 electrical_steel   │     1 copper             │   0.6 prismarine         │   -44 electrum           │    15 ma.prosperity      │  0.38 thorium            │  0.63 ma.prosperity      │     0 certus_quartz      ║
║    54 rubber             │   104 obsidian            │  2.27 sponge             │  1.88 bone               │     1 livingrock         │  0.63 ma.inferium        │   -44 pink_slime         │    15 malachite_gem      │   0.4 knightslime        │   0.7 desert_myrmex      │     0 construction_alloy ║
║    58 livingwood         │   113 flint               │  2.42 endstone           │  1.88 meat_metal         │     1 nagascale          │   0.7 desert_myrmex      │   -17 plague_metal       │    15 peridot            │   0.4 lead               │   0.7 essence_metal      │     0 essence_metal      ║
║    59 blueslime          │   113 signalum            │  2.63 ardite             │  2.17 flint              │     1 rubber             │   0.7 fierymetal         │   -17 psigem             │    15 restonia_crystal   │   0.4 osmium             │   0.7 jungle_myrmex      │     0 firewood           ║
║    61 aquamarine         │   113 tin                 │  2.63 vibrant_alloy      │  2.25 copper             │     1 slime              │   0.7 jungle_myrmex      │   -17 psimetal           │    15 ruby               │   0.4 steel              │  0.75 mica               │     0 flux_crystal       ║
║    61 cheese             │   118 magnesium           │  2.81 livingwood         │  2.25 electrum           │     1 sponge             │   0.7 lead               │   -10 heavy              │    15 stone              │   0.4 terrasteel         │  0.75 sponge             │     0 livingrock         ║
║    61 pink_slime         │   128 livingrock          │     3 apatite            │  2.25 netherrack         │     1 tin                │   0.7 signalum           │    -9 redstone_alloy     │    15 tin                │   0.4 topaz              │   0.8 ardite             │     0 livingwood         ║
║    61 tanzanite          │   128 primal_metal        │     3 cactus             │  2.25 polyethylene       │     2 carbon_fiber       │   0.7 slime              │     0 dreamwood          │    15 treatedwood        │   0.4 uranium            │   0.8 energetic_alloy    │     0 mica               ║
║    64 endstone           │   131 aquamarine          │     3 cheese             │  2.25 stone              │     2 certus_quartz      │   0.7 tanzanite          │     0 emerald_plustic    │    15 xu_demonic_metal   │  0.43 boron              │   0.8 platinum           │     0 nagascale          ║
║    64 prismarine         │   135 rubber              │     3 desert_myrmex      │  2.42 endstone           │     2 conductive_iron    │  0.75 boron_nitride      │     0 endstone           │    18 boron              │  0.45 ardite             │   0.8 restonia_crystal   │     0 palis_crystal      ║
║    65 ma.prosperity      │   135 steeleaf            │     3 jungle_myrmex      │  2.55 cactus             │     2 constantan         │  0.75 certus_quartz      │     0 palis_crystal      │    19 aquamarine         │   0.5 desert_myrmex      │   0.8 silver             │     0 pink_slime         ║
║    65 soularium          │   135 thorium             │     3 peridot            │  2.63 bronze             │     2 desert_myrmex      │  0.75 electrical_steel   │     0 pigiron            │    19 certus_quartz      │   0.5 energetic_alloy    │   0.8 void_metal         │     0 polyethylene       ║
║    66 energetic_alloy    │   136 palis_crystal       │     3 pink_slime         │  2.63 dreamwood          │     2 electrical_steel   │  0.75 nickel             │     0 primal_metal       │    19 litherite          │   0.5 hard_carbon        │  0.85 pink_slime         │     0 redstone_alloy     ║
║    67 certus_quartz      │   136 restonia_crystal    │     3 stone              │  2.63 lead               │     2 essence_metal      │  0.75 restonia_crystal   │     0 ruby               │    19 steel              │   0.5 invar              │   0.9 cactus             │     0 restonia_crystal   ║
║    68 essence_metal      │   145 uranium             │  3.02 blueslime          │  2.63 magnesium          │     2 firewood           │  0.75 sentient_metal     │     0 signalum           │    19 tanzanite          │   0.5 iron               │   0.9 conductive_iron    │     0 rubber             ║
║    68 palis_crystal      │   150 bone                │  3.18 slime              │  2.63 xu_enchanted_metal │     2 fluix              │  0.75 thorium            │     0 slime              │    23 dreamwood          │   0.5 jungle_myrmex      │   0.9 electrical_steel   │     0 slime              ║
║    68 slime              │   150 certus_quartz       │  3.19 meat_metal         │   2.7 ardite             │     2 jungle_myrmex      │  0.78 ma.prudentium      │     0 tanzanite          │    23 fluix              │   0.5 ma.base_essence    │   0.9 fierymetal         │     0 soularium          ║
║    68 sponge             │   152 starmetal           │  3.38 livingrock         │     3 aluminium          │     2 litherite          │   0.8 apatite            │     0 titanium           │    23 psigem             │   0.5 magnesium          │   0.9 livingrock         │     0 sponge             ║
║    68 void_crystal       │   153 iron                │  3.38 netherrack         │     3 aquamarine         │     2 livingwood         │   0.8 aquamarine         │     0 universal_metal    │    23 psimetal           │   0.5 manasteel          │  0.99 ma.inferium        │     0 tin                ║
║    69 desert_myrmex      │   158 cactus              │  3.38 tin                │     3 iron               │     2 ma.soulium         │   0.8 black_quartz       │     0 void_crystal       │    23 tough              │   0.5 meat_metal         │     1 aethium            │     0 treatedwood        ║
║    69 jungle_myrmex      │   158 copper              │  3.38 void_crystal       │     3 litherite          │     2 nickel             │   0.8 energetic_metal    │     0 void_metal         │    26 aluminium          │   0.5 sky_stone          │     1 aquamarine         │     0 universal_metal    ║
║    69 sky_stone          │   165 polyethylene        │  3.45 ruby               │     3 livingrock         │     2 plague_metal       │   0.8 iridium            │     0 xu_evil_metal      │    26 apatite            │   0.5 starmetal          │     1 black_quartz       │     0 void_crystal       ║
║    69 treatedwood        │   165 vibrant_alloy       │   3.6 palis_crystal      │     3 mica               │     2 sentient_metal     │   0.8 lumium             │     1 livingwood         │    26 livingrock         │  0.55 bronze             │     1 blueslime          │     0 wood               ║
║    70 copper             │   169 aluminium           │  3.75 essence_metal      │     3 sky_stone          │     2 sky_stone          │   0.8 ma.soulium         │     4 lumium             │    30 constantan         │  0.55 tough              │     1 carbon_fiber       │     0 xu_magical_wood    ║
║    71 firewood           │   183 ma.base_essence     │  3.75 flint              │     3 tin                │     2 steeleaf           │   0.8 mica               │     4 paper              │    30 flint              │  0.58 ma.inferium        │     1 certus_quartz      │   0.5 pladium            ║
║    72 malachite_gem      │   188 lumium              │  3.75 mica               │     3 uranium            │     2 treatedwood        │   0.8 osmium             │     6 chocolate          │    30 manasteel          │   0.6 bound_metal        │     1 crystal_matrix     │   0.8 ma.prosperity      ║
║    72 plague_metal       │   188 silver              │  3.75 polyethylene       │  3.08 cobalt             │     2 uranium            │   0.8 platinum           │     6 ma.prosperity      │    30 polyethylene       │   0.6 copper             │     1 electrum           │   0.9 emerald_plustic    ║
║    73 magmaslime         │   192 void_crystal        │  3.75 rubber             │  3.15 obsidian           │     2 void_crystal       │   0.8 refined_glowstone  │     8 apatite            │    30 titanium           │   0.6 dragonbone         │     1 emerald_plustic    │     1 aluminium          ║
║    76 conductive_iron    │   203 manasteel           │  3.75 sapphire           │  3.15 restonia_crystal   │     3 advanced_alloy     │   0.8 steeleaf           │     8 aquamarine         │    32 endstone           │   0.6 iridium            │     1 energetic_metal    │     1 ardite             ║
║    76 constantan         │   203 netherrack          │  3.75 silver             │  3.18 thaumium           │     3 bronze             │   0.8 tin                │     8 constantan         │    34 erodium            │   0.6 livingrock         │     1 firewood           │     1 dreamwood          ║
║    76 dragonbone         │   206 constantan          │  3.75 sky_stone          │  3.23 nagascale          │     3 dragonbone         │   0.8 topaz              │     8 construction_alloy │    34 sentient_metal     │   0.6 nagascale          │     1 flux_crystal       │     1 electrical_steel   ║
║    76 peridot            │   206 fluix               │  3.75 treatedwood        │  3.25 ma.base_essence    │     3 energetic_alloy    │   0.8 uranium            │     8 livingrock         │    35 hard_carbon        │   0.6 osgloglas          │     1 infinity_metal     │     1 energetic_alloy    ║
║    77 electrical_steel   │   206 mica                │  3.75 weezer             │  3.38 apatite            │     3 energetic_metal    │   0.8 void_crystal       │     8 restonia_crystal   │    38 cactus             │   0.6 pigiron            │     1 livingwood         │     1 ionite             ║
║    77 litherite          │   210 black_quartz        │  3.82 bone               │  3.38 certus_quartz      │     3 enori_crystal      │  0.85 boron              │     8 tin                │    38 draconium          │  0.65 alumite            │     1 pink_metal         │     1 kyronite           ║
║    78 fluix              │   225 cheese              │  3.93 osmiridium         │  3.38 constantan         │     3 erodium            │  0.85 cactus             │    11 fluix              │    38 energetic_metal    │  0.65 amethyst           │     1 primal_metal       │     1 magmaslime         ║
║    78 lead               │   225 dragonbone          │  3.94 lead               │  3.38 fluix              │     3 fierymetal         │  0.85 endstone           │    15 black_quartz       │    38 essence_metal      │  0.65 ma.soulium         │     1 signalum           │     1 void_metal         ║
║    80 mica               │   225 litherite           │  3.98 copper             │  3.38 ma.inferium        │     3 fluix_steel        │  0.85 iron               │    15 cactus             │    38 invar              │  0.65 manyullyn          │     1 vibrant_alloy      │  1.25 conductive_iron    ║
║    80 obsidian           │   225 nickel              │  4.13 prismarine         │  3.38 pigiron            │     3 iron               │  0.85 magmaslime         │    15 essence_metal      │    38 iron               │  0.65 nickel             │     1 wood               │   1.5 carbon_fiber       ║
║    80 silver             │   225 refined_glowstone   │  4.35 knightslime        │  3.38 signalum           │     3 kyronite           │  0.85 netherrack         │    15 invar              │    38 ma.base_essence    │  0.65 refined_obsidian   │     1 xu_magical_wood    │   1.5 erodium            ║
║    81 black_quartz       │   225 sentient_metal      │   4.5 amethyst           │  3.38 thorium            │     3 lonsdaleite        │   0.9 aluminium          │    15 litherite          │    38 manyullyn          │   0.7 enori_crystal      │  1.05 ionite             │   1.5 lonsdaleite        ║
║    81 ma.soulium         │   230 electrical_steel    │   4.5 carbon_fiber       │  3.45 ma.soulium         │     3 malachite_gem      │   0.9 cobalt             │    15 sky_stone          │    38 rubber             │   0.7 fluix_steel        │  1.05 magmaslime         │   1.5 plague_metal       ║
║    81 nickel             │   240 enori_crystal       │   4.5 certus_quartz      │  3.75 black_quartz       │     3 netherrack         │   0.9 dark_steel         │    15 xu_enchanted_metal │    38 sky_stone          │   0.7 thaumium           │   1.1 aluminium          │   1.5 sentient_metal     ║
║    82 sentient_metal     │   244 erodium             │   4.5 constantan         │  3.75 elementium         │     3 palis_crystal      │   0.9 end_steel          │    19 aluminium          │    41 enori_crystal      │   0.7 xu_demonic_metal   │   1.1 draconium          │  1.91 ma.inferium        ║
║    84 ruby               │   255 sky_stone           │   4.5 elementium         │  3.75 erodium            │     3 peridot            │   0.9 fluix_steel        │    19 mica               │    41 refined_glowstone  │  0.73 ma.prudentium      │   1.1 dreamwood          │     2 advanced_alloy     ║
║    85 steeleaf           │   255 void_metal          │   4.5 firewood           │  3.75 essence_metal      │     3 prismarine         │   0.9 flux_crystal       │    19 polyethylene       │    45 diamantine_crystal │  0.75 aquamarine         │   1.1 palis_crystal      │     2 aethium            ║
║    86 uranium            │   259 ma.inferium         │   4.5 fluix              │  3.75 manasteel          │     3 pulsating_iron     │   0.9 livingrock         │    19 wood               │    45 nickel             │  0.75 cobalt             │   1.1 pladium            │     2 chocolate          ║
║    88 erodium            │   263 kyronite            │   4.5 iron               │  3.75 psigem             │     3 redstone_alloy     │   0.9 manasteel          │    19 xu_magical_wood    │    45 vibrant_alloy      │  0.75 constantan         │   1.1 xu_demonic_metal   │     2 crystal_matrix     ║
║    88 iron               │   263 xu_enchanted_metal  │   4.5 manasteel          │  3.75 psimetal           │     3 restonia_crystal   │   0.9 obsidian           │    23 certus_quartz      │    47 ma.soulium         │  0.75 elementium         │  1.13 treatedwood        │     2 desert_myrmex      ║
║    91 ardite             │   281 apatite             │   4.5 osgloglas          │  3.75 refined_glowstone  │     3 ruby               │   0.9 steel              │    23 copper             │    49 bone               │  0.75 enderium           │  1.15 bone               │     2 enori_crystal      ║
║    92 xu_demonic_metal   │   281 pladium             │   4.5 pulsating_iron     │  3.75 sentient_metal     │     3 sapphire           │  0.95 silver             │    23 diamantine_crystal │    49 kyronite           │  0.75 energetic_metal    │  1.15 kyronite           │     2 fluxed_electrum    ║
║    93 nagascale          │   285 pigiron             │   4.5 topaz              │  3.75 silver             │     3 tanzanite          │  0.97 ma.intermedium     │    23 lonsdaleite        │    49 topaz              │  0.75 litherite          │  1.15 lumium             │     2 jungle_myrmex      ║
║    94 kyronite           │   300 desert_myrmex       │  4.65 pigiron            │  3.75 treatedwood        │     3 topaz              │     1 advanced_alloy     │    23 osmiridium         │    50 xu_evil_metal      │  0.75 palis_crystal      │   1.2 diamantine_crystal │     2 knightslime        ║
║    94 sapphire           │   300 essence_metal       │  4.76 ma.soulium         │  3.83 knightslime        │     3 xu_magical_wood    │     1 aethium            │    23 refined_glowstone  │    53 emerald_plustic    │  0.75 sentient_metal     │   1.2 dragonbone         │     2 litherite          ║
║    95 carbon_fiber       │   300 ionite              │  4.88 black_quartz       │  3.94 livingwood         │     4 amethyst           │     1 bound_metal        │    23 sentient_metal     │    56 electrical_steel   │  0.75 vibrant_alloy      │   1.2 erodium            │     2 lumium             ║
║    96 manasteel          │   300 jungle_myrmex       │  4.88 electrical_steel   │  4.05 palis_crystal      │     4 black_quartz       │     1 elementium         │    23 thaumium           │    56 emeraldic_crystal  │   0.8 fluxed_electrum    │   1.2 lonsdaleite        │     2 nickel             ║
║    98 fluix_steel        │   300 thaumium            │  4.88 fluix_steel        │  4.13 advanced_alloy     │     4 bound_metal        │     1 enori_crystal      │    26 erodium            │    56 fluix_steel        │  0.85 advanced_alloy     │   1.2 manyullyn          │     2 silver             ║
║    98 ma.inferium        │   315 endstone            │  4.88 invar              │  4.13 alumite            │     4 dark_steel         │     1 erodium            │    26 nickel             │    56 lonsdaleite        │  0.85 draconic_metal     │   1.2 weezer             │     2 sky_stone          ║
║    98 xu_enchanted_metal │   319 aethium             │  4.88 litherite          │  4.13 carbon_fiber       │     4 diamantine_crystal │     1 firewood           │    30 bound_metal        │    56 ma.inferium        │  0.85 emeraldic_crystal  │  1.25 advanced_alloy     │     2 steeleaf           ║
║    99 bronze             │   319 invar               │  4.88 nickel             │  4.13 desert_myrmex      │     4 electrum           │     1 fluix              │    30 cheese             │    56 netherrack         │  0.85 erodium            │  1.25 constantan         │  2.32 ma.prudentium      ║
║    99 flux_crystal       │   323 bronze              │  4.99 ma.base_essence    │  4.13 firewood           │     4 emerald_plustic    │     1 hard_carbon        │    30 energetic_metal    │    60 alumite            │  0.85 slime              │  1.25 elementium         │   2.5 draconium          ║
║    99 vibrant_alloy      │   323 prismarine          │  5.06 conductive_iron    │  4.13 fluix_steel        │     4 emeraldic_crystal  │     1 infinity_metal     │    30 flux_crystal       │    60 bound_metal        │  0.85 titanium           │  1.25 fluix              │     3 cobalt             ║
║   101 aluminium          │   326 lead                │   5.1 alumite            │  4.13 invar              │     4 flux_crystal       │     1 ionite             │    30 mirion             │    60 bronze             │   0.9 dragonsteel_fire   │  1.25 fluxed_electrum    │     3 constantan         ║
║   101 knightmetal        │   338 fluix_steel         │   5.1 bronze             │  4.13 jungle_myrmex      │     4 fluxed_electrum    │     1 kyronite           │    37 magnesium          │    60 elementium         │   0.9 dragonsteel_ice    │  1.25 litherite          │     3 lead               ║
║   101 lonsdaleite        │   345 nagascale           │  5.25 advanced_alloy     │  4.13 lumium             │     4 knightmetal        │     1 litherite          │    38 bone               │    60 flux_crystal       │   0.9 fluix              │  1.25 refined_glowstone  │   3.1 ma.soulium         ║
║   102 topaz              │   353 bound_metal         │  5.25 aquamarine         │  4.13 nickel             │     4 lead               │     1 livingwood         │    38 draconium          │    60 xu_enchanted_metal │   0.9 lonsdaleite        │  1.25 sentient_metal     │   3.5 energetic_metal    ║
║   102 void_metal         │   375 flux_crystal        │  5.25 dark_steel         │  4.13 osmium             │     4 ma.prosperity      │     1 magnesium          │    38 emeraldic_crystal  │    64 pladium            │   0.9 tin                │  1.25 sky_stone          │   3.5 magnesium          ║
║   104 advanced_alloy     │   375 osmium              │  5.25 draconium          │   4.2 energetic_alloy    │     4 manasteel          │     1 neutronium         │    38 end_steel          │    68 mirion             │   0.9 wyvern_metal       │  1.25 tin                │  3.52 ma.base_essence    ║
║   104 pigiron            │   384 draconium           │  5.25 dragonsteel_fire   │   4.5 diamantine_crystal │     4 pladium            │     1 pink_metal         │    38 kyronite           │    68 obsidian           │  0.95 bone               │  1.25 universal_metal    │     4 bound_metal        ║
║   105 pladium            │   384 energetic_metal     │  5.25 dragonsteel_ice    │   4.5 dragonbone         │     4 silver             │     1 pladium            │    38 ma.inferium        │    68 steeleaf           │  0.95 draconium          │   1.3 cobalt             │     4 diamantine_crystal ║
║   108 emerald_plustic    │   405 steel               │  5.25 emerald_plustic    │   4.5 energetic_metal    │     4 thaumium           │     1 primal_metal       │    38 manasteel          │    71 carbon_fiber       │  0.95 kyronite           │   1.3 emeraldic_crystal  │     4 dragonbone         ║
║   108 invar              │   413 dark_steel          │  5.25 erodium            │   4.5 knightmetal        │     4 void_metal         │     1 redstone_alloy     │    38 refined_obsidian   │    71 void_metal         │     1 aluminium          │   1.3 fluix_steel        │     4 electrum           ║
║   109 draconium          │   413 firewood            │  5.25 flux_crystal       │   4.5 kyronite           │     4 weezer             │     1 sapphire           │    38 silver             │    75 amethyst           │     1 diamantine_crystal │   1.3 lead               │     4 fierymetal         ║
║   109 fierymetal         │   450 end_steel           │  5.25 knightmetal        │   4.5 lonsdaleite        │     5 draconium          │     1 sky_stone          │    41 ma.soulium         │    75 copper             │     1 fierymetal         │   1.3 slime              │     4 fluix              ║
║   110 energetic_metal    │   450 magmaslime          │  5.25 lonsdaleite        │   4.5 plague_metal       │     5 elementium         │     1 terrasteel         │    42 thorium            │    75 lead               │     1 firewood           │   1.3 titanium           │     4 malachite_gem      ║
║   112 elementium         │   465 psigem              │  5.25 psigem             │   4.5 steel              │     5 end_steel          │     1 thaumium           │    45 fluix_steel        │    75 ma.prudentium      │     1 lumium             │   1.3 wyvern_metal       │     4 manyullyn          ║
║   112 knightslime        │   465 psimetal            │  5.25 psimetal           │   4.5 steeleaf           │     5 endstone           │     1 treatedwood        │    45 iron               │    75 osgloglas          │     1 platinum           │  1.34 ma.prudentium      │     4 peridot            ║
║   112 pulsating_iron     │   466 ma.soulium          │  5.25 sentient_metal     │   4.5 titanium           │     5 heavy              │     1 wood               │    45 starmetal          │    75 platinum           │     1 psigem             │  1.35 enori_crystal      │     4 pink_metal         ║
║   114 bound_metal        │   480 malachite_gem       │  5.25 steel              │   4.5 topaz              │     5 invar              │     1 xu_evil_metal      │    45 uranium            │    75 prismarine         │     1 psimetal           │  1.35 refined_obsidian   │     4 psigem             ║
║   115 psigem             │   480 peridot             │  5.25 steeleaf           │   4.5 void_crystal       │     5 ionite             │     1 xu_magical_wood    │    49 ma.base_essence    │    79 ionite             │     1 refined_glowstone  │   1.4 bound_metal        │     4 psimetal           ║
║   115 psimetal           │   488 tanzanite           │  5.25 thaumium           │   4.5 void_metal         │     5 ma.base_essence    │  1.05 copper             │    49 pladium            │    83 thaumium           │     1 sapphire           │   1.4 malachite_gem      │     4 refined_glowstone  ║
║   117 diamantine_crystal │   492 boron               │  5.25 xu_enchanted_metal │  4.58 malachite_gem      │     5 ma.inferium        │  1.05 pulsating_iron     │    53 alumite            │    90 fluxed_electrum    │     1 treatedwood        │   1.4 peridot            │     4 ruby               ║
║   117 fluxed_electrum    │   495 ruby                │  5.27 ma.inferium        │  4.58 peridot            │     5 magmaslime         │   1.1 alumite            │    53 bronze             │    90 sapphire           │     1 wood               │   1.4 pigiron            │     4 sapphire           ║
║   117 lumium             │   500 infinity_metal      │  5.27 manyullyn          │  4.62 osmiridium         │     5 meat_metal         │   1.1 bone               │    53 carbon_fiber       │    90 terrasteel         │     1 xu_magical_wood    │   1.4 ruby               │     4 uranium            ║
║   119 ionite             │   500 xu_evil_metal       │   5.3 obsidian           │  4.65 prismarine         │     5 osmium             │   1.1 bronze             │    53 enori_crystal      │    94 aethium            │  1.05 blueslime          │   1.4 topaz              │     4 xu_demonic_metal   ║
║   120 amethyst           │   518 energetic_alloy     │   5.4 fierymetal         │   4.8 ruby               │     5 pigiron            │   1.1 constantan         │    53 topaz              │    94 knightslime        │  1.05 cactus             │  1.45 copper             │  4.02 ma.intermedium     ║
║   120 primal_metal       │   518 ma.prudentium       │  5.63 diamantine_crystal │   4.8 sapphire           │     5 pink_metal         │   1.1 draconium          │    56 ma.prudentium      │   113 cheese             │  1.05 pladium            │   1.5 boron_nitride      │   4.5 boron              ║
║   121 osmium             │   518 topaz               │  5.63 kyronite           │  4.88 platinum           │     5 primal_metal       │   1.1 dreamwood          │    56 rubber             │   113 desert_myrmex      │  1.07 ma.intermedium     │   1.5 bronze             │   4.5 thorium            ║
║   122 steel              │   525 alumite             │  5.63 osmium             │  4.95 fierymetal         │     5 steel              │   1.1 electrum           │    60 electrical_steel   │   113 end_steel          │   1.1 dreamwood          │   1.5 enderium           │     5 copper             ║
║   122 thaumium           │   525 elementium          │  5.63 uranium            │  4.97 ma.prudentium      │     5 universal_metal    │   1.1 emerald_plustic    │    60 ionite             │   113 firewood           │   1.1 emerald_plustic    │   1.5 iron               │     5 hard_carbon        ║
║   124 alumite            │   525 sapphire            │     6 boron              │  4.99 starmetal          │     6 alumite            │   1.1 mirion             │    68 fluxed_electrum    │   113 jungle_myrmex      │   1.1 magmaslime         │   1.5 ma.base_essence    │     5 tough              ║
║   125 ma.prudentium      │   540 fierymetal          │     6 bound_metal        │  5.25 bound_metal        │     6 knightslime        │   1.1 palis_crystal      │    71 aethium            │   113 ma.intermedium     │   1.1 pink_metal         │   1.5 ma.soulium         │     5 vibrant_alloy      ║
║   127 ma.base_essence    │   585 blueslime           │     6 emeraldic_crystal  │  5.25 emerald_plustic    │     6 lumium             │   1.1 plague_metal       │    75 amethyst           │   113 magmaslime         │  1.15 certus_quartz      │   1.5 manasteel          │   5.5 boron_nitride      ║
║   128 weezer             │   585 cobalt              │     6 enderium           │  5.25 emeraldic_crystal  │     6 ma.prudentium      │   1.1 tough              │    75 cobalt             │   113 redstone_alloy     │  1.15 ionite             │   1.5 mirion             │   5.5 iridium            ║
║   129 enori_crystal      │   585 plague_metal        │     6 fluxed_electrum    │  5.25 fluxed_electrum    │     6 mica               │   1.1 xu_enchanted_metal │    75 conductive_iron    │   113 silver             │  1.15 sponge             │   1.5 nickel             │   5.5 mirion             ║
║   130 dark_steel         │   600 advanced_alloy      │     6 pladium            │  5.25 magmaslime         │     6 obsidian           │  1.12 ma.superium        │    75 elementium         │   120 boron_nitride      │   1.2 black_quartz       │   1.5 sapphire           │  5.94 ma.superium        ║
║   130 emeraldic_crystal  │   600 fluxed_electrum     │     6 terrasteel         │  5.25 pladium            │     6 platinum           │  1.16 osmiridium         │    75 knightmetal        │   128 pigiron            │   1.2 chaotic_metal      │   1.5 starmetal          │     6 bronze             ║
║   130 thorium            │   615 manyullyn           │     6 void_metal         │  5.25 primal_metal       │     6 refined_glowstone  │   1.2 lonsdaleite        │    75 ma.intermedium     │   131 osmium             │   1.2 flux_crystal       │   1.5 steeleaf           │     6 dragonsteel_fire   ║
║   135 manyullyn          │   630 lonsdaleite         │  6.01 ma.prudentium      │  5.25 tanzanite          │     6 signalum           │   1.2 pigiron            │    75 sapphire           │   135 enderium           │   1.2 livingwood         │   1.5 thorium            │     6 dragonsteel_ice    ║
║   137 electrum           │   638 knightslime         │  6.38 energetic_metal    │  5.59 end_steel          │     6 titanium           │   1.2 ruby               │    75 steeleaf           │   135 plague_metal       │   1.2 silver             │   1.6 alumite            │     6 emeraldic_crystal  ║
║   137 refined_glowstone  │   675 knightmetal         │  6.38 ionite             │  5.63 enori_crystal      │     7 ardite             │   1.2 sponge             │    75 weezer             │   150 blueslime          │   1.2 steeleaf           │   1.6 draconic_metal     │     6 fluix_steel        ║
║   145 boron              │   690 pulsating_iron      │  6.38 refined_obsidian   │  5.63 terrasteel         │     7 cobalt             │  1.25 conductive_iron    │    75 xu_demonic_metal   │   150 dragonbone         │  1.21 ma.superium        │   1.6 psigem             │     6 invar              ║
║   150 magnesium          │   720 diamantine_crystal  │  6.48 starmetal          │     6 amethyst           │     7 hard_carbon        │  1.25 diamantine_crystal │    90 platinum           │   150 fierymetal         │  1.25 aethium            │   1.6 psimetal           │     6 osmium             ║
║   151 signalum           │   743 ardite              │  6.68 nagascale          │     6 draconium          │     7 ma.intermedium     │  1.25 emeraldic_crystal  │    91 treatedwood        │   150 wyvern_metal       │  1.25 universal_metal    │   1.6 uranium            │     6 pulsating_iron     ║
║   154 aethium            │   750 slime               │  6.75 aethium            │     6 flux_crystal       │     7 psigem             │  1.25 enderium           │    94 chaotic_metal      │   169 advanced_alloy     │  1.25 void_crystal       │  1.63 ma.intermedium     │     6 wyvern_metal       ║
║   155 platinum           │   788 sponge              │  6.75 enori_crystal      │     6 ionite             │     7 psimetal           │  1.25 invar              │    94 crystal_matrix     │   169 ma.superium        │   1.3 pink_slime         │   1.7 amethyst           │   6.5 amethyst           ║
║   160 refined_obsidian   │   825 amethyst            │  6.75 iridium            │     6 refined_obsidian   │     7 starmetal          │  1.25 knightmetal        │    94 pink_metal         │   188 conductive_iron    │  1.33 ma.supremium       │   1.7 boron              │   6.6 titanium           ║
║   162 osmiridium         │   825 refined_obsidian    │  6.75 lumium             │  6.38 iridium            │     7 tough              │  1.25 pink_slime         │    98 dragonbone         │   188 dark_steel         │  1.35 mirion             │  1.75 invar              │     7 alumite            ║
║   167 osgloglas          │   836 tough               │  6.75 mirion             │  6.38 pink_metal         │     7 xu_demonic_metal   │  1.25 refined_obsidian   │   102 boron              │   188 electrum           │   1.4 ma.prosperity      │  1.75 osmium             │     7 elementium         ║
║   173 mirion             │   848 emeraldic_crystal   │  6.75 platinum           │  6.48 dark_steel         │     7 xu_enchanted_metal │   1.3 blueslime          │   113 dark_steel         │   188 pink_metal         │   1.4 malachite_gem      │  1.75 terrasteel         │     7 enderium           ║
║   174 tough              │   900 carbon_fiber        │  6.75 primal_metal       │  6.54 manyullyn          │     8 boron              │   1.3 carbon_fiber       │   113 enderium           │   188 pulsating_iron     │   1.4 peridot            │   1.8 osgloglas          │     7 iron               ║
║   175 starmetal          │   900 pink_slime          │  6.75 thorium            │   6.6 osgloglas          │     8 ma.superium        │   1.3 dragonbone         │   113 osmium             │   188 sponge             │   1.4 void_metal         │   1.8 thaumium           │     7 manasteel          ║
║   176 enderium           │   917 emerald_plustic     │   7.5 aluminium          │  6.75 aethium            │     8 magnesium          │   1.3 malachite_gem      │   113 steel              │   208 palis_crystal      │   1.5 cheese             │   1.8 void_crystal       │     7 pigiron            ║
║   178 cobalt             │   975 osmiridium          │   7.5 refined_glowstone  │  6.75 boron              │     8 manyullyn          │   1.3 peridot            │   120 iridium            │   225 cobalt             │   1.5 conductive_iron    │  1.91 ma.superium        │     7 refined_obsidian   ║
║   181 terrasteel         │  1035 ma.intermedium      │   7.5 tough              │  6.75 enderium           │     8 mirion             │   1.3 psigem             │   124 ma.superium        │   225 draconic_metal     │   1.5 crystal_matrix     │     2 chaotic_metal      │     7 topaz              ║
║   183 restonia_crystal   │  1050 platinum            │  8.25 hard_carbon        │  6.75 mirion             │     8 osmiridium         │   1.3 psimetal           │   131 advanced_alloy     │   225 ma.supremium       │   1.5 electrical_steel   │     2 cheese             │  7.32 ma.supremium       ║
║   184 ma.intermedium     │  1121 hard_carbon         │  8.25 magnesium          │  6.75 vibrant_alloy      │     8 refined_obsidian   │  1.35 ma.supremium       │   135 terrasteel         │   225 pink_slime         │   1.5 electrum           │     2 hard_carbon        │     8 platinum           ║
║   186 iridium            │  1125 dragonsteel_fire    │  8.31 ma.intermedium     │  6.92 ma.intermedium     │     8 thorium            │   1.4 ardite             │   144 boron_nitride      │   225 refined_obsidian   │   1.5 essence_metal      │     2 iridium            │     8 primal_metal       ║
║   191 hard_carbon        │  1125 dragonsteel_ice     │     9 boron_nitride      │  7.13 crystal_matrix     │     8 xu_evil_metal      │   1.4 ma.prosperity      │   150 ma.supremium       │   255 chaotic_metal      │   1.5 paper              │     2 knightslime        │     8 weezer             ║
║   191 xu_evil_metal      │  1125 weezer              │     9 cobalt             │   7.5 hard_carbon        │     9 boron_nitride      │   1.5 amethyst           │   174 tough              │   255 iridium            │   1.5 primal_metal       │     2 magnesium          │   8.2 osgloglas          ║
║   195 pink_metal         │  1166 soularium           │     9 electrum           │   7.5 tough              │     9 dragonsteel_fire   │   1.5 cheese             │   188 manyullyn          │   263 slime              │   1.5 restonia_crystal   │     2 nagascale          │     9 dark_steel         ║
║   195 universal_metal    │  1238 terrasteel          │     9 wyvern_metal       │   7.5 universal_metal    │     9 dragonsteel_ice    │   1.5 crystal_matrix     │   188 pulsating_iron     │   300 crystal_matrix     │   1.5 ruby               │     2 steel              │     9 steel              ║
║   225 boron_nitride      │  1275 enderium            │  9.38 pink_metal         │   7.5 weezer             │     9 osgloglas          │   1.5 essence_metal      │   188 sponge             │   300 energetic_alloy    │   1.5 weezer             │  2.05 osmiridium         │     9 terrasteel         ║
║   246 crystal_matrix     │  1342 pink_metal          │  9.49 titanium           │  8.25 boron_nitride      │     9 vibrant_alloy      │   1.5 osgloglas          │   188 wyvern_metal       │   300 knightmetal        │   1.6 carbon_fiber       │   2.2 tough              │   9.5 thaumium           ║
║   250 titanium           │  1420 titanium            │  9.75 crystal_matrix     │  8.72 ma.superium        │    10 aethium            │   1.5 starmetal          │   225 desert_myrmex      │   315 universal_metal    │  1.75 mica               │  2.35 ma.supremium       │    10 draconic_metal     ║
║   251 wyvern_metal       │  1425 iridium             │  9.75 neutronium         │  8.99 xu_demonic_metal   │    10 enderium           │   1.5 weezer             │   225 draconic_metal     │   338 ardite             │  1.75 polyethylene       │   2.5 dark_steel         │    10 osmiridium         ║
║   260 end_steel          │  1439 mirion              │  9.75 signalum           │  9.75 xu_evil_metal      │    10 iridium            │   1.5 wyvern_metal       │   225 jungle_myrmex      │   375 starmetal          │     2 plague_metal       │   2.5 end_steel          │ 10.98 end_steel          ║
║   300 ma.superium        │  1605 wyvern_metal        │  9.75 xu_evil_metal      │ 11.25 wyvern_metal       │    10 ma.supremium       │  1.75 draconic_metal     │   233 hard_carbon        │   375 weezer             │     2 rubber             │     3 dragonsteel_fire   │    12 starmetal          ║
║   356 dragonsteel_fire   │  1680 osgloglas           │  10.5 restonia_crystal   │ 11.27 ma.supremium       │    11 crystal_matrix     │   1.8 void_metal         │   300 dragonsteel_fire   │   383 dragonsteel_fire   │   2.5 redstone_alloy     │     3 dragonsteel_ice    │    13 heavy              ║
║   356 dragonsteel_ice    │  1736 boron_nitride       │ 11.25 universal_metal    │    12 neutronium         │    11 terrasteel         │     2 energetic_alloy    │   300 dragonsteel_ice    │   383 dragonsteel_ice    │     3 construction_alloy │     3 plague_metal       │    18 chaotic_metal      ║
║   362 neutronium         │  2070 ma.superium         │ 11.32 end_steel          │    13 heavy              │    12 neutronium         │     2 universal_metal    │   300 fierymetal         │   500 infinity_metal     │     5 signalum           │   3.5 pulsating_iron     │    20 neutronium         ║
║   471 ma.supremium       │  2400 crystal_matrix      │  12.4 ma.superium        │ 26.25 draconic_metal     │    12 wyvern_metal       │   2.2 chaotic_metal      │   375 knightslime        │   600 osmiridium         │  6.66 infinity_metal     │     4 neutronium         │   300 infinity_metal     ║
║   493 draconic_metal     │  2738 draconic_metal      │  13.5 draconic_metal     │  31.5 dragonsteel_fire   │    13 draconic_metal     │  2.45 ma.base_essence    │   416 neutronium         │   730 mica               │   NaN apatite            │   NaN apatite            │   NaN apatite            ║
║   950 chaotic_metal      │  4140 ma.supremium        │  16.5 chaotic_metal      │  31.5 dragonsteel_ice    │    14 chaotic_metal      │   2.5 meat_metal         │   500 infinity_metal     │   833 neutronium         │   NaN knightmetal        │   NaN knightmetal        │   NaN knightmetal        ║
║ 19531 infinity_metal     │  4995 chaotic_metal       │ 16.69 ma.supremium       │    48 chaotic_metal      │    15 infinity_metal     │   2.8 titanium           │  1125 soularium          │   938 soularium          │   NaN xu_enchanted_metal │   NaN xu_enchanted_metal │   NaN xu_enchanted_metal ║
║   NaN heavy              │  8333 neutronium          │    25 infinity_metal     │   300 infinity_metal     │   NaN aquamarine         │   NaN nagascale          │   NaN nagascale          │   NaN nagascale          │   NaN xu_evil_metal      │   NaN xu_evil_metal      │   NaN xu_evil_metal      ║
╟──────────────────────────┼───────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────╢
║ Total Power              │ HeadDurability            │ MiningSpeed              │ AttackDamage             │ HarvestLevel             │ HandleModifier           │ HandleDurability         │ ExtraDurability          │ DrawSpeed                │ Range                    │ BonusDamage              ║
╚══════════════════════════╧═══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╝


