Armory Stat Tweaks
╔════════════════════════════╤════════════════════════════╤════════════════════════════╤════════════════════════════╤════════════════════════════╤════════════════════════════╤════════════════════════════╗
║ Total Power                │ CoreDurability             │ Defense                    │ Modifier                   │ PlatesDurability           │ Toughness                  │ ExtraDurability            ║
║                            │ sqrt((n+10)*10)            │ n*0.5                      │ sqrt((n+1)*10)             │ n*0.3                      │ (n+2)**2                   │ n*0.5                      ║
╟────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────╢
║    18 paper                │     0 paper                │  0.34 ma.prosperity        │   0.1 paper                │   -21 ardite               │     0 alpha_fur            │     0 chocolate            ║
║    19 chocolate            │     1 chocolate            │  0.38 paper                │   0.3 heavy                │   -21 firewood             │     0 aluminium            │     0 endorium             ║
║    21 wood                 │     1 ma.prosperity        │  0.75 sponge               │   0.5 knightslime          │   -21 magmaslime           │     0 amber                │     0 ghostwood            ║
║    22 netherrack           │     1 treatedwood          │   0.9 chocolate            │   0.5 polyethylene         │   -17 netherrack           │     0 apatite              │     0 nagascale            ║
║    22 stone                │     1 universal_metal      │  1.35 blueslime            │   0.5 rubber               │   -17 prismarine           │     0 aquamarine           │     0 wolframium           ║
║    23 apatite              │     1 xu_magical_wood      │   1.5 slime                │   0.5 stone                │   -14 obsidian             │     0 cactus               │   0.4 heavy                ║
║    23 ma.prosperity        │   1.5 meat_metal           │  2.25 livingwood           │   0.6 flint                │    -9 flint                │     0 certus_quartz        │     1 aluminium            ║
║    23 void_crystal         │     2 apatite              │  2.25 wood                 │   0.6 fluxed_electrum      │    -5 blueslime            │     0 cheese               │     1 constantan           ║
║    24 ghostwood            │     2 construction_alloy   │   2.5 heavy                │   0.6 prismarine           │    -5 lead                 │     0 chocolate            │     1 construction_alloy   ║
║    24 livingwood           │     2 polyethylene         │     3 bone                 │  0.63 chitinbrowndeathworm │    -5 stone                │     0 cobalt               │     1 draconium            ║
║    24 polyethylene         │     2 wood                 │     3 pink_slime           │  0.63 chitintandeathworm   │    -2 electrum             │     0 conductive_iron      │     1 enchanted_fabric     ║
║    25 construction_alloy   │     3 electrum             │  3.38 alpha_fur            │  0.63 chitinwhitedeathworm │     0 chocolate            │     0 constantan           │     1 fluix_steel          ║
║    25 dreamwood            │     3 mica                 │  3.38 construction_alloy   │  0.65 chocolate            │     0 endorium             │     0 construction_alloy   │     1 invar                ║
║    25 flint                │     3 void_crystal         │  3.38 flint                │   0.7 lead                 │     0 endstone             │     0 copper               │     1 livingwood           ║
║    25 heavy                │     3 xu_demonic_metal     │  3.38 soularium            │   0.7 slime                │     0 essence_metal        │     0 darkwood             │     1 paper                ║
║    25 tin                  │     4 conductive_iron      │  3.56 apatite              │  0.75 bloodwood            │     0 iridium              │     0 desert_myrmex        │     1 primal_metal         ║
║    26 palis_crystal        │     4 dreamwood            │  3.75 polyethylene         │  0.75 boron_nitride        │     0 livingrock           │     0 dragonbone           │     1 sky_stone            ║
║    26 rubber               │     4 ghostwood            │  3.75 stone                │  0.75 certus_quartz        │     0 lumium               │     0 dragonsteel_fire     │     1 steel                ║
║    27 aluminium            │     4 refined_glowstone    │  3.98 netherrack           │  0.75 livingwood           │     0 meat_metal           │     0 dragonsteel_ice      │     1 stone                ║
║    27 electrum             │     5 aquamarine           │  4.22 conductive_iron      │  0.75 nickel               │     0 nagascale            │     0 dreamwood            │     1 tin                  ║
║    27 enchanted_fabric     │     5 bloodwood            │   4.5 ghostwood            │  0.75 restonia_crystal     │     0 palis_crystal        │     0 electrical_steel     │     1 wood                 ║
║    27 restonia_crystal     │     5 erodium              │  4.88 dreamwood            │  0.75 sentient_metal       │     0 paper                │     0 electrum             │     2 apatite              ║
║    28 aquamarine           │     5 litherite            │  4.88 sky_stone            │  0.75 thorium              │     0 pigiron              │     0 elementium           │     2 black_quartz         ║
║    28 cactus               │     5 palis_crystal        │  5.06 redstone_alloy       │  0.78 carbon_fiber         │     0 pink_slime           │     0 enchanted_fabric     │     2 chitinbrowndeathworm ║
║    28 constantan           │     5 redstone_alloy       │  5.25 rubber               │   0.8 apatite              │     0 primal_metal         │     0 end_steel            │     2 chitintandeathworm   ║
║    28 sky_stone            │     5 restonia_crystal     │  5.25 void_crystal         │   0.8 aquamarine           │     0 signalum             │     0 endorium             │     2 chitinwhitedeathworm ║
║    28 treatedwood          │     6 kyronite             │  5.63 meat_metal           │   0.8 black_quartz         │     0 slime                │     0 energetic_alloy      │     2 dreamwood            ║
║    29 copper               │     6 tin                  │     6 copper               │   0.8 energetic_metal      │     0 universal_metal      │     0 energetic_metal      │     2 enderium             ║
║    29 essence_metal        │     7 magnesium            │  6.08 electrum             │   0.8 mica                 │     0 void_crystal         │     0 enori_crystal        │     2 endstone             ║
║    29 xu_magical_wood      │     7 pladium              │  6.75 cheese               │   0.8 osmium               │     0 void_metal           │     0 erodium              │     2 essence_metal        ║
║    30 bone                 │     7 sky_stone            │  6.75 endstone             │   0.8 platinum             │     0 wolframium           │     0 essence_metal        │     2 flint                ║
║    30 certus_quartz        │     7 stone                │  6.75 pulsating_iron       │   0.8 refined_glowstone    │     1 aluminium            │     0 fierymetal           │     2 leatherforesttroll   ║
║    30 firewood             │     8 aethium              │  6.75 tin                  │   0.8 tin                  │     1 cactus               │     0 fluix                │     2 leatherfrosttroll    ║
║    30 iron                 │     8 black_quartz         │  6.75 treatedwood          │   0.8 uranium              │     1 constantan           │     0 ghostwood            │     2 leathermountaintroll ║
║    30 litherite            │     8 certus_quartz        │  6.75 xu_magical_wood      │   0.8 void_crystal         │     1 construction_alloy   │     0 heavy                │     2 livingrock           ║
║    30 livingrock           │     8 enchanted_fabric     │   7.2 carbon_fiber         │  0.85 boron                │     1 draconium            │     0 iron                 │     2 ma.prosperity        ║
║    30 magnesium            │     8 enori_crystal        │   7.5 aluminium            │  0.85 cactus               │     1 elementium           │     0 jungle_myrmex        │     2 malachite_gem        ║
║    30 nickel               │     8 flint                │   7.5 cactus               │  0.85 endstone             │     1 enchanted_fabric     │     0 knightmetal          │     2 mica                 ║
║    31 endstone             │     8 fluix                │   7.5 palis_crystal        │  0.85 iron                 │     1 enderium             │     0 litherite            │     2 nickel               ║
║    31 erodium              │     8 ionite               │   7.5 restonia_crystal     │  0.85 magmaslime           │     1 invar                │     0 livingwood           │     2 platinum             ║
║    31 fluix                │     8 obsidian             │  7.59 electrical_steel     │  0.85 manasteel            │     1 livingwood           │     0 ma.base_essence      │     2 polyethylene         ║
║    31 manasteel            │     8 rubber               │   7.8 livingrock           │  0.85 netherrack           │     1 polyethylene         │     0 ma.prosperity        │     2 psigem               ║
║    32 alpha_fur            │     8 starmetal            │  8.25 lead                 │   0.9 aluminium            │     1 sky_stone            │     0 ma.soulium           │     2 psimetal             ║
║    32 black_quartz         │     8 thorium              │     9 bronze               │   0.9 cobalt               │     1 tin                  │     0 malachite_gem        │     2 rubber               ║
║    32 mica                 │     8 uranium              │     9 constantan           │   0.9 enchanted_fabric     │     1 wood                 │     0 manasteel            │     2 tanzanite            ║
║    32 universal_metal      │     8 vibrant_alloy        │     9 enchanted_fabric     │   0.9 fluix_steel          │     2 apatite              │     0 mica                 │     2 treatedwood          ║
║    32 uranium              │     9 aluminium            │  9.38 aquamarine           │   0.9 lonsdaleite          │     2 copper               │     0 mirion               │     2 void_crystal         ║
║    33 elementium           │     9 bone                 │  9.38 magnesium            │   0.9 obsidian             │     2 crystal_matrix       │     0 nagascale            │     2 xu_demonic_metal     ║
║    33 enori_crystal        │     9 copper               │  9.75 ardite               │   0.9 steel                │     2 dreamwood            │     0 netherrack           │     2 xu_magical_wood      ║
║    34 thorium              │     9 iron                 │  9.75 black_quartz         │  0.95 silver               │     2 ghostwood            │     0 nickel               │     3 cactus               ║
║    35 invar                │     9 livingwood           │  9.75 essence_metal        │     1 advanced_alloy       │     2 malachite_gem        │     0 osgloglas            │     3 calebronzeseaserpent ║
║    35 meat_metal           │     9 ma.base_essence      │ 10.35 refined_obsidian     │     1 aethium              │     2 mica                 │     0 palis_crystal        │     3 calepurpleseaserpent ║
║    35 osmium               │     9 steeleaf             │  10.5 calebronzeseaserpent │     1 alumite              │     2 nickel               │     0 paper                │     3 certus_quartz        ║
║    36 energetic_metal      │    10 cactus               │  10.5 calepurpleseaserpent │     1 bound_metal          │     2 platinum             │     0 plague_metal         │     3 fusewood             ║
║    36 kyronite             │    10 constantan           │  10.5 chitinbrowndeathworm │     1 dark_matter          │     2 psigem               │     0 psigem               │     3 iron                 ║
║    36 prismarine           │    10 heavy                │  10.5 chitintandeathworm   │     1 emerald_plustic      │     2 psimetal             │     0 psimetal             │     3 ledeepblueseaserpent ║
║    36 sentient_metal       │    10 manasteel            │  10.5 chitinwhitedeathworm │     1 enori_crystal        │     2 tanzanite            │     0 pulsating_iron       │     3 manasteel            ║
║    37 bronze               │    10 sentient_metal       │  10.5 leatherforesttroll   │     1 erodium              │     2 treatedwood          │     0 redstone_alloy       │     3 manyullyn            ║
║    37 cobalt               │    10 silver               │  10.5 leatherfrosttroll    │     1 firewood             │     2 xu_demonic_metal     │     0 restonia_crystal     │     3 palis_crystal        ║
║    37 draconium            │    11 alpha_fur            │  10.5 leathermountaintroll │     1 fluix                │     2 xu_magical_wood      │     0 rubber               │     3 scaleblueseaserpent  ║
║    37 lead                 │    11 alumite              │  10.5 ledeepblueseaserpent │     1 flux_crystal         │     3 aquamarine           │     0 soularium            │     3 scalegreenseaserpent ║
║    37 pigiron              │    11 bound_metal          │  10.5 nickel               │     1 hard_carbon          │     3 black_quartz         │     0 steeleaf             │     3 scaleredseaserpent   ║
║    37 refined_glowstone    │    11 cheese               │  10.5 osmium               │     1 infinity_metal       │     3 bone                 │     0 stone                │     3 scaletealseaserpent  ║
║    38 bloodwood            │    11 chitinbrowndeathworm │  10.5 scaleblueseaserpent  │     1 ionite               │     3 carbon_fiber         │     0 tanzanite            │  3.96 iridium              ║
║    38 blueslime            │    11 chitintandeathworm   │  10.5 scalegreenseaserpent │     1 kyronite             │     3 fluix                │     0 thaumium             │     4 aquamarine           ║
║    38 darkwood             │    11 chitinwhitedeathworm │  10.5 scaleredseaserpent   │     1 litherite            │     3 litherite            │     0 tin                  │     4 bone                 ║
║    38 electrical_steel     │    11 dragonbone           │  10.5 scaletealseaserpent  │     1 magnesium            │     3 magnesium            │     0 titanium             │     4 darkwood             ║
║    38 redstone_alloy       │    11 electrical_steel     │ 10.88 uranium              │     1 manyullyn            │     3 refined_obsidian     │     0 topaz                │     4 fluix                ║
║    39 slime                │    11 essence_metal        │ 11.25 bloodwood            │     1 neutronium           │     3 restonia_crystal     │     0 treatedwood          │     4 litherite            ║
║    40 magmaslime           │    11 fluix_steel          │ 11.25 certus_quartz        │     1 peridot              │     3 rubber               │     0 universal_metal      │     4 ma.soulium           ║
║    41 boron                │    11 flux_crystal         │ 11.25 elementium           │     1 pink_metal           │     3 silver               │     0 vibrant_alloy        │     4 magnesium            ║
║    41 knightslime          │    11 ma.soulium           │ 11.25 enori_crystal        │     1 pladium              │     3 thorium              │     0 void_crystal         │     4 restonia_crystal     ║
║    41 leatherforesttroll   │    11 netherrack           │ 11.25 iron                 │     1 primal_metal         │     3 uranium              │     0 weezer               │     4 scalebluedragon      ║
║    41 leatherfrosttroll    │    11 nickel               │ 11.25 manasteel            │     1 red_matter           │     3 wyvern_metal         │     0 wolframium           │     4 scalebronzedragon    ║
║    41 leathermountaintroll │    11 peridot              │ 11.63 fluix                │     1 ruby                 │     4 bloodwood            │     0 wood                 │     4 scalegraydragon      ║
║    42 cheese               │    11 pigiron              │ 11.63 thorium              │     1 sapphire             │     4 boron                │     0 xu_demonic_metal     │     4 scalegreendragon     ║
║    42 chitinbrowndeathworm │    11 ruby                 │  11.7 cobalt               │     1 sky_stone            │     4 darkwood             │     0 xu_enchanted_metal   │     4 scalereddragon       ║
║    42 chitintandeathworm   │    11 sapphire             │ 11.81 xu_enchanted_metal   │     1 terrasteel           │     4 erodium              │     0 xu_evil_metal        │     4 scalesapphiredragon  ║
║    42 chitinwhitedeathworm │    12 boron                │    12 invar                │     1 wood                 │     4 iron                 │     0 xu_magical_wood      │     4 scalesilverdragon    ║
║    42 pladium              │    12 bronze               │    12 sentient_metal       │  1.05 copper               │     4 kyronite             │  0.15 magnesium            │     4 scalewhitedragon     ║
║    42 silver               │    12 darkwood             │    12 signalum             │   1.1 bone                 │     4 ma.soulium           │  0.25 amethyst             │     4 thorium              ║
║    43 conductive_iron      │    12 draconium            │ 12.15 obsidian             │   1.1 bronze               │     5 aethium              │  0.25 livingrock           │     4 uranium              ║
║    43 fluix_steel          │    12 endstone             │ 12.53 pigiron              │   1.1 constantan           │     5 alumite              │  0.25 meat_metal           │   4.8 carbon_fiber         ║
║    43 ma.base_essence      │    12 energetic_metal      │ 12.75 litherite            │   1.1 draconium            │     5 bronze               │  0.38 firewood             │     5 bloodwood            ║
║    43 wolframium           │    12 fusewood             │ 12.75 lumium               │   1.1 electrum             │     5 certus_quartz        │  0.38 osmium               │     5 boron                ║
║    44 carbon_fiber         │    12 lead                 │ 12.75 silver               │   1.1 palis_crystal        │     5 energetic_metal      │  0.38 polyethylene         │     5 boron_nitride        ║
║    44 hard_carbon          │    12 prismarine           │ 12.83 knightslime          │   1.1 tough                │     5 heavy                │  0.53 uranium              │     5 bronze               ║
║    44 ma.soulium           │    12 signalum             │ 13.13 firewood             │  1.15 iridium              │     5 ionite               │  0.75 black_quartz         │     5 elementium           ║
║    44 obsidian             │  12.6 carbon_fiber         │  13.5 fluix_steel          │   1.2 elementium           │     5 ma.base_essence      │  0.75 bone                 │     5 erodium              ║
║    44 xu_enchanted_metal   │ 12.98 tough                │  13.5 flux_crystal         │   1.2 pigiron              │     5 osmium               │  0.75 draconium            │     5 hard_carbon          ║
║    45 alumite              │    13 firewood             │  13.5 refined_glowstone    │   1.2 sponge               │     5 peridot              │  0.75 endstone             │     5 ionite               ║
║    45 lonsdaleite          │    13 ma.inferium          │  13.5 scalebluedragon      │  1.25 diamantine_crystal   │     5 pladium              │  0.75 flint                │     5 kyronite             ║
║    45 peridot              │    13 primal_metal         │  13.5 scalebronzedragon    │  1.25 dreamwood            │     5 refined_glowstone    │  0.75 invar                │     5 ma.base_essence      ║
║    45 platinum             │    13 steel                │  13.5 scalegraydragon      │  1.25 emeraldic_crystal    │     5 ruby                 │  0.75 knightslime          │     5 netherrack           ║
║    45 ruby                 │    13 xu_enchanted_metal   │  13.5 scalegreendragon     │  1.25 enderium             │     5 sapphire             │  0.75 kyronite             │     5 obsidian             ║
║    45 sapphire             │    14 diamantine_crystal   │  13.5 scalereddragon       │  1.25 invar                │     5 sentient_metal       │  0.75 lonsdaleite          │     5 pink_metal           ║
║    45 signalum             │    14 elementium           │  13.5 scalesapphiredragon  │  1.25 leatherforesttroll   │     5 topaz                │  0.75 pigiron              │     5 pladium              ║
║    46 nagascale            │    14 emerald_plustic      │  13.5 scalesilverdragon    │  1.25 leatherfrosttroll    │     5 vibrant_alloy        │  0.75 sentient_metal       │     5 refined_glowstone    ║
║    46 pink_slime           │    14 fluxed_electrum      │  13.5 scalewhitedragon     │  1.25 leathermountaintroll │     5 xu_evil_metal        │  0.75 sky_stone            │     5 terrasteel           ║
║    46 refined_obsidian     │    14 livingrock           │  13.5 universal_metal      │  1.25 pink_slime           │     6 boron_nitride        │  0.83 thorium              │     5 topaz                ║
║    46 xu_demonic_metal     │    14 magmaslime           │ 13.52 starmetal            │  1.25 refined_obsidian     │     6 bound_metal          │   0.9 boron                │     5 vibrant_alloy        ║
║    47 lumium               │    14 osmium               │  13.8 steel                │  1.25 sunnarium            │     6 cobalt               │  0.94 bronze               │     5 void_metal           ║
║    48 diamantine_crystal   │    14 wolframium           │ 13.88 erodium              │   1.3 blueslime            │     6 electrical_steel     │     1 lumium               │     5 xu_evil_metal        ║
║    48 emerald_plustic      │ 14.04 hard_carbon          │  14.1 prismarine           │   1.4 ardite               │     6 enori_crystal        │     1 ma.inferium          │     6 aethium              ║
║    48 fluxed_electrum      │    15 blueslime            │ 14.51 nagascale            │   1.4 signalum             │     6 fluix_steel          │     1 signalum             │     6 copper               ║
║    48 psigem               │    15 cobalt               │ 14.55 magmaslime           │  1.45 ma.prosperity        │     6 fusewood             │  1.13 hard_carbon          │     6 crystal_matrix       ║
║    48 psimetal             │    15 desert_myrmex        │ 14.61 ma.base_essence      │   1.5 crystal_matrix       │     6 manasteel            │  1.13 leatherforesttroll   │     6 electrical_steel     ║
║    49 endorium             │    15 jungle_myrmex        │    15 alumite              │   1.5 essence_metal        │     6 pink_metal           │  1.13 leatherfrosttroll    │     6 lead                 ║
║    50 advanced_alloy       │    15 knightslime          │    15 bound_metal          │   1.5 gelid_enderium       │     6 tough                │  1.13 leathermountaintroll │     6 osmium               ║
║    50 manyullyn            │    15 leatherforesttroll   │    15 emerald_plustic      │   1.5 livingrock           │   6.4 osgloglas            │  1.13 refined_glowstone    │     6 prismarine           ║
║    50 thaumium             │    15 leatherfrosttroll    │    15 energetic_metal      │   1.5 wyvern_metal         │     7 draconic_metal       │   1.5 advanced_alloy       │     6 sentient_metal       ║
║    51 ardite               │    15 leathermountaintroll │    15 kyronite             │  1.59 alpha_fur            │     7 emerald_plustic      │   1.5 bloodwood            │     6 tough                ║
║    51 iridium              │    15 manyullyn            │    15 lonsdaleite          │   1.6 lumium               │     7 flux_crystal         │   1.5 diamantine_crystal   │     6 wyvern_metal         ║
║    51 malachite_gem        │    15 sunnarium            │    15 manyullyn            │   1.6 spectre              │     7 hard_carbon          │   1.5 fluxed_electrum      │   6.4 osgloglas            ║
║    51 tough                │ 15.99 thaumium             │    15 peridot              │   1.8 draconic_metal       │     7 ma.prosperity        │   1.5 lead                 │     7 bound_metal          ║
║    52 ionite               │    16 ardite               │    15 ruby                 │   1.8 ghostwood            │     7 osmiridium           │   1.5 ma.prudentium        │     7 knightslime          ║
║    54 pink_metal           │    16 emeraldic_crystal    │    15 sapphire             │   1.8 void_metal           │     7 sunnarium            │   1.5 pladium              │     7 osmiridium           ║
║    54 tanzanite            │    16 invar                │    15 thaumium             │  1.88 scalebluedragon      │     7 xu_enchanted_metal   │   1.5 platinum             │     7 xu_enchanted_metal   ║
║    54 topaz                │    16 lonsdaleite          │ 15.19 ma.inferium          │  1.88 scalebronzedragon    │     8 advanced_alloy       │   1.5 prismarine           │     8 alpha_fur            ║
║    55 pulsating_iron       │    16 lumium               │ 15.53 ma.soulium           │  1.88 scalegraydragon      │     8 alpha_fur            │   1.5 silver               │     8 alumite              ║
║    55 steeleaf             │    16 slime                │ 15.75 diamantine_crystal   │  1.88 scalegreendragon     │     8 amber                │   1.5 slime                │     8 amber                ║
║    56 amber                │    16 sponge               │ 15.75 platinum             │  1.88 scalereddragon       │     8 diamantine_crystal   │  1.65 alumite              │     8 energetic_metal      ║
║    56 desert_myrmex        │    16 void_metal           │ 15.75 terrasteel           │  1.88 scalesapphiredragon  │     8 starmetal            │  1.65 emerald_plustic      │     8 enori_crystal        ║
║    56 emeraldic_crystal    │    16 wyvern_metal         │ 16.13 crystal_matrix       │  1.88 scalesilverdragon    │     8 steel                │  1.65 peridot              │     8 firewood             ║
║    56 enderium             │    17 pink_slime           │ 16.13 pladium              │  1.88 scalewhitedragon     │     8 terrasteel           │  1.65 ruby                 │     8 magmaslime           ║
║    56 fusewood             │  17.4 refined_obsidian     │ 16.45 wolframium           │     2 gelid_gem            │     9 fluxed_electrum      │  1.65 sapphire             │     8 peridot              ║
║    56 jungle_myrmex        │    18 advanced_alloy       │  16.5 advanced_alloy       │     2 universal_metal      │     9 thaumium             │  1.69 blueslime            │     8 pigiron              ║
║    56 ma.inferium          │  18.9 iridium              │  16.5 fluxed_electrum      │   2.2 chaotic_metal        │     9 titanium             │  1.69 chitinbrowndeathworm │     8 refined_obsidian     ║
║    57 bound_metal          │    19 crystal_matrix       │  16.5 pink_metal           │     3 fusewood             │    10 emeraldic_crystal    │  1.69 chitintandeathworm   │     8 ruby                 ║
║    57 flux_crystal         │    21 dark_steel           │ 16.86 xu_demonic_metal     │  3.13 calebronzeseaserpent │    10 manyullyn            │  1.69 chitinwhitedeathworm │     8 sapphire             ║
║    57 vibrant_alloy        │    21 terrasteel           │ 16.88 emeraldic_crystal    │  3.13 calepurpleseaserpent │    10 sponge               │   1.8 iridium              │     8 silver               ║
║    58 crystal_matrix       │    23 calebronzeseaserpent │ 16.88 psigem               │  3.13 ledeepblueseaserpent │    10 steeleaf             │  1.88 fluix_steel          │     8 starmetal            ║
║    58 steel                │    23 calepurpleseaserpent │ 16.88 psimetal             │  3.13 scaleblueseaserpent  │    11 chitinbrowndeathworm │  1.88 magmaslime           │     9 blueslime            ║
║    58 void_metal           │    23 ledeepblueseaserpent │ 16.88 wyvern_metal         │  3.13 scalegreenseaserpent │    11 chitintandeathworm   │  1.88 refined_obsidian     │     9 flux_crystal         ║
║    59 dragonbone           │    23 nagascale            │ 17.25 ionite               │  3.13 scaleredseaserpent   │    11 chitinwhitedeathworm │     2 ma.intermedium       │     9 sunnarium            ║
║    60 scalebluedragon      │    23 psigem               │    18 dark_matter          │  3.13 scaletealseaserpent  │    11 lonsdaleite          │     2 spectre              │     9 thaumium             ║
║    60 scalebronzedragon    │    23 psimetal             │    18 darkwood             │   3.5 meat_metal           │    12 chaotic_metal        │  2.03 tough                │     9 titanium             ║
║    60 scalegraydragon      │    23 scaleblueseaserpent  │    18 draconium            │   3.6 darkwood             │    12 ma.inferium          │   2.2 osmiridium           │    10 diamantine_crystal   ║
║    60 scalegreendragon     │    23 scalegreenseaserpent │    18 neutronium           │   4.5 construction_alloy   │    12 mirion               │  2.25 carbon_fiber         │    10 electrum             ║
║    60 scalereddragon       │    23 scaleredseaserpent   │ 18.38 aethium              │   4.5 soularium            │    13 amethyst             │  2.25 emeraldic_crystal    │    10 sponge               ║
║    60 scalesapphiredragon  │    23 scaletealseaserpent  │ 18.38 enderium             │  5.63 conductive_iron      │    13 cheese               │  2.25 fusewood             │    10 steeleaf             ║
║    60 scalesilverdragon    │    24 dark_matter          │ 18.56 desert_myrmex        │  6.48 treatedwood          │    13 desert_myrmex        │  2.25 manyullyn            │    11 advanced_alloy       ║
║    60 scalewhitedragon     │    24 malachite_gem        │ 18.56 jungle_myrmex        │  6.75 redstone_alloy       │    13 jungle_myrmex        │  2.25 pink_metal           │    11 cobalt               ║
║    61 calebronzeseaserpent │    25 pink_metal           │  18.9 energetic_alloy      │     9 cheese               │    13 knightslime          │  2.25 pink_slime           │    11 draconic_metal       ║
║    61 calepurpleseaserpent │    25 tanzanite            │ 19.13 boron                │     9 pulsating_iron       │    13 redstone_alloy       │  2.25 scalebluedragon      │    11 emerald_plustic      ║
║    61 ledeepblueseaserpent │    25 xu_evil_metal        │ 19.24 amber                │     9 xu_magical_wood      │    15 leatherforesttroll   │  2.25 scalebronzedragon    │    11 emeraldic_crystal    ║
║    61 scaleblueseaserpent  │    26 draconic_metal       │ 20.25 dark_steel           │ 10.13 electrical_steel     │    15 leatherfrosttroll    │  2.25 scalegraydragon      │    11 fluxed_electrum      ║
║    61 scalegreenseaserpent │    26 energetic_alloy      │ 20.25 dragonbone           │ 15.75 xu_enchanted_metal   │    15 leathermountaintroll │  2.25 scalegreendragon     │    11 pink_slime           ║
║    61 scaleredseaserpent   │    26 ma.prudentium        │ 20.25 endorium             │    18 starmetal            │    15 plague_metal         │  2.25 scalereddragon       │    11 slime                ║
║    61 scaletealseaserpent  │    26 platinum             │ 20.25 hard_carbon          │ 19.48 ma.base_essence      │    16 ma.prudentium        │  2.25 scalesapphiredragon  │    11 universal_metal      ║
║    62 sponge               │    26 topaz                │ 20.25 plague_metal         │ 20.25 ma.inferium          │    17 dragonbone           │  2.25 scalesilverdragon    │    12 ardite               ║
║    62 sunnarium            │    27 endorium             │ 20.25 steeleaf             │  20.7 ma.soulium           │    18 dark_matter          │  2.25 scalewhitedragon     │    12 ma.inferium          ║
║    63 plague_metal         │    27 scalebluedragon      │ 20.25 sunnarium            │ 22.24 endorium             │    21 conductive_iron      │   2.5 ma.superium          │    12 mirion               ║
║    67 titanium             │    27 scalebronzedragon    │ 20.25 topaz                │ 22.24 wolframium           │    21 dark_steel           │  2.63 enderium             │    13 amethyst             ║
║    68 xu_evil_metal        │    27 scalegraydragon      │ 20.59 malachite_gem        │  22.5 end_steel            │    21 pulsating_iron       │  2.63 ionite               │    13 cheese               ║
║    69 aethium              │    27 scalegreendragon     │ 21.38 tough                │  22.5 psigem               │    22 fierymetal           │  2.63 obsidian             │    13 desert_myrmex        ║
║    71 starmetal            │    27 scalereddragon       │ 22.34 ma.prudentium        │  22.5 psimetal             │    22 gelid_gem            │  2.75 void_metal           │    13 jungle_myrmex        ║
║    73 ma.prudentium        │    27 scalesapphiredragon  │  22.5 boron_nitride        │    23 thaumium             │    23 calebronzeseaserpent │  2.81 calebronzeseaserpent │    13 lonsdaleite          ║
║    73 osgloglas            │    27 scalesilverdragon    │  22.5 mica                 │ 24.75 desert_myrmex        │    23 calepurpleseaserpent │  2.81 calepurpleseaserpent │    13 redstone_alloy       ║
║    75 energetic_alloy      │    27 scalewhitedragon     │  22.5 void_metal           │ 24.75 jungle_myrmex        │    23 ledeepblueseaserpent │  2.81 ledeepblueseaserpent │    15 chaotic_metal        ║
║    76 boron_nitride        │    28 amber                │  23.3 spectre              │  25.2 energetic_alloy      │    23 scaleblueseaserpent  │  2.81 scaleblueseaserpent  │    15 plague_metal         ║
║    77 end_steel            │    28 enderium             │ 23.63 tanzanite            │ 25.65 amber                │    23 scalegreenseaserpent │  2.81 scalegreenseaserpent │    16 ma.prudentium        ║
║    77 terrasteel           │    28 gelid_gem            │ 24.75 primal_metal         │  25.8 nagascale            │    23 scaleredseaserpent   │  2.81 scaleredseaserpent   │    17 dragonbone           ║
║    78 fierymetal           │    29 plague_metal         │ 24.91 titanium             │    27 dark_steel           │    23 scaletealseaserpent  │  2.81 scaletealseaserpent  │    20 meat_metal           ║
║    81 dark_matter          │    30 end_steel            │ 25.92 iridium              │    27 dragonbone           │    26 end_steel            │  2.88 crystal_matrix       │    21 conductive_iron      ║
║    84 osmiridium           │    32 boron_nitride        │    27 fusewood             │    27 plague_metal         │    26 gelid_enderium       │     3 ardite               │    21 dark_matter          ║
║    86 dark_steel           │    35 pulsating_iron       │    27 knightmetal          │    27 titanium             │    26 ma.intermedium       │     3 bound_metal          │    21 dark_steel           ║
║    87 amethyst             │    36 fierymetal           │    27 red_matter           │    27 topaz                │    27 red_matter           │     3 dark_steel           │    21 lumium               ║
║    96 knightmetal          │    36 gelid_enderium       │  29.7 fierymetal           │ 27.45 malachite_gem        │    27 scalebluedragon      │     3 flux_crystal         │    21 pulsating_iron       ║
║    96 mirion               │    36 red_matter           │  29.7 osgloglas            │ 29.79 ma.prudentium        │    27 scalebronzedragon    │     3 ma.supremium         │    21 signalum             ║
║    97 wyvern_metal         │    41 chaotic_metal        │ 30.38 vibrant_alloy        │  31.5 tanzanite            │    27 scalegraydragon      │     3 sunnarium            │    22 fierymetal           ║
║    98 ma.intermedium       │ 44.25 soularium            │ 31.15 ma.intermedium       │    36 knightmetal          │    27 scalegreendragon     │  3.38 steel                │    26 end_steel            ║
║   101 weezer               │    46 knightmetal          │ 33.75 end_steel            │    36 osmiridium           │    27 scalereddragon       │   3.5 starmetal            │    26 gelid_gem            ║
║   110 dragonsteel_fire     │    50 osmiridium           │ 33.75 weezer               │    36 steeleaf             │    27 scalesapphiredragon  │  3.75 dark_matter          │    26 ma.intermedium       ║
║   110 dragonsteel_ice      │    53 ma.intermedium       │ 34.02 osmiridium           │  39.6 fierymetal           │    27 scalesilverdragon    │  3.75 sponge               │    32 gelid_enderium       ║
║   111 primal_metal         │    57 dragonsteel_fire     │  34.5 gelid_gem            │  39.6 osgloglas            │    27 scalewhitedragon     │  3.99 boron_nitride        │    32 red_matter           ║
║   120 soularium            │    57 dragonsteel_ice      │  37.5 ma.superium          │ 39.96 xu_demonic_metal     │    33 energetic_alloy      │  4.13 aethium              │    33 energetic_alloy      ║
║   124 ma.superium          │    57 weezer               │  37.5 ma.supremium         │  40.5 vibrant_alloy        │    38 ma.superium          │   4.5 terrasteel           │    38 ma.superium          ║
║   128 red_matter           │    63 titanium             │  37.5 xu_evil_metal        │ 41.53 ma.intermedium       │    41 weezer               │     6 gelid_enderium       │    41 weezer               ║
║   134 gelid_enderium       │    64 amethyst             │ 39.38 draconic_metal       │    45 weezer               │    42 dragonsteel_fire     │     6 red_matter           │    42 dragonsteel_fire     ║
║   138 ma.supremium         │    72 osgloglas            │  40.5 gelid_enderium       │    50 dragonsteel_fire     │    42 dragonsteel_ice      │     6 wyvern_metal         │    42 dragonsteel_ice      ║
║   144 spectre              │    90 ma.superium          │  41.5 amethyst             │    50 dragonsteel_ice      │    44 knightmetal          │  6.88 primal_metal         │    44 knightmetal          ║
║   208 draconic_metal       │    90 ma.supremium         │ 45.56 mirion               │    50 ma.superium          │    50 ma.supremium         │  10.5 draconic_metal       │    50 ma.supremium         ║
║   218 gelid_gem            │ 109.5 mirion               │ 46.88 dragonsteel_fire     │    50 ma.supremium         │    83 neutronium           │  10.5 gelid_gem            │    70 spectre              ║
║   347 neutronium           │   200 spectre              │ 46.88 dragonsteel_ice      │    50 xu_evil_metal        │   100 spectre              │ 11.25 neutronium           │    83 neutronium           ║
║   570 chaotic_metal        │   500 infinity_metal       │ 69.75 infinity_metal       │  54.5 amethyst             │   104 soularium            │ 20.25 chaotic_metal        │   104 soularium            ║
║  1535 infinity_metal       │   833 neutronium           │    72 chaotic_metal        │ 60.75 mirion               │   500 infinity_metal       │    30 infinity_metal       │   500 infinity_metal       ║
╟────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────╢
║ Total Power                │ CoreDurability             │ Defense                    │ Modifier                   │ PlatesDurability           │ Toughness                  │ ExtraDurability            ║
╚════════════════════════════╧════════════════════════════╧════════════════════════════╧════════════════════════════╧════════════════════════════╧════════════════════════════╧════════════════════════════╝


Arrow Shaft Stat Tweaks
╔════════════════════╤════════════════════╤════════════════════╗
║ Total Power        │ Modifier           │ BonusAmmo          ║
║                    │ n*10.0             │ n*0.2              ║
╟────────────────────┼────────────────────┼────────────────────╢
║     0 heavy        │   0.2 heavy        │   -10 heavy        ║
║     7 endrod       │   0.6 steeleaf     │     0 bloodwood    ║
║     8 fierymetal   │   0.7 endrod       │     0 fierymetal   ║
║     8 steeleaf     │  0.75 polyethylene │     0 ice          ║
║     9 blaze        │   0.8 blaze        │     0 livingwood   ║
║    10 bone         │   0.8 fierymetal   │     0 tnt          ║
║    10 ice          │   0.9 bone         │     0 treatedwood  ║
║    10 livingwood   │   0.9 ghostwood    │     0 wood         ║
║    10 tnt          │  0.95 ice          │     1 endrod       ║
║    10 wood         │  0.95 tnt          │     1 wolframium   ║
║    11 amber        │     1 amber        │     2 dragonbone   ║
║    11 ghostwood    │     1 darkwood     │     3 blaze        ║
║    12 darkwood     │     1 livingwood   │     4 fusewood     ║
║    12 treatedwood  │     1 wood         │     5 amber        ║
║    13 dragonbone   │  1.05 reed         │     5 bone         ║
║    13 fusewood     │   1.2 treatedwood  │     5 endorium     ║
║    13 reed         │  1.25 dreamwood    │    10 darkwood     ║
║    14 wolframium   │  1.25 fusewood     │    10 reed         ║
║    15 bloodwood    │   1.3 dragonbone   │    10 steeleaf     ║
║    15 endorium     │   1.4 endorium     │    12 ghostwood    ║
║    15 polyethylene │   1.4 nagascale    │    20 nagascale    ║
║    18 dreamwood    │   1.4 wolframium   │    25 dreamwood    ║
║    18 nagascale    │   1.5 bloodwood    │    38 polyethylene ║
╟────────────────────┼────────────────────┼────────────────────╢
║ Total Power        │ Modifier           │ BonusAmmo          ║
╚════════════════════╧════════════════════╧════════════════════╝


Bowstring Stat Tweaks
╔════════════════════════╤════════════════════════╗
║ Total Power            │ Modifier               ║
║                        │ n*10.0                 ║
╟────────────────────────┼────────────────────────╢
║     9 enchanted_fabric │   0.9 enchanted_fabric ║
║    10 hemp             │     1 hemp             ║
║    10 string           │     1 string           ║
║    11 slimevine_blue   │  1.05 vine             ║
║    11 slimevine_purple │   1.1 slimevine_blue   ║
║    11 vine             │   1.1 slimevine_purple ║
║    13 fluxed_string    │  1.25 fluxed_string    ║
║    13 mana_string      │   1.3 mana_string      ║
║    14 string_cheese    │   1.4 string_cheese    ║
║    20 soularium        │     2 soularium        ║
║    22 spectre_string   │   2.2 spectre_string   ║
╟────────────────────────┼────────────────────────╢
║ Total Power            │ Modifier               ║
╚════════════════════════╧════════════════════════╝


Fletching Stat Tweaks
╔══════════════════════════╤══════════════════════════╤══════════════════════════╗
║ Total Power              │ Accuracy                 │ Modifier                 ║
║                          │ n*40.0                   │ n*10.0                   ║
╟──────────────────────────┼──────────────────────────┼──────────────────────────╢
║    35 leaf               │   0.5 leaf               │   0.7 amphithere_feather ║
║    43 amphithere_feather │   0.8 slimeleaf_blue     │   0.8 steeleaf           ║
║    45 slimeleaf_blue     │   0.8 slimeleaf_orange   │   0.9 ghostwood          ║
║    45 slimeleaf_orange   │   0.8 slimeleaf_purple   │     1 feather            ║
║    45 slimeleaf_purple   │   0.9 amphithere_feather │  1.15 raven_feather      ║
║    48 steeleaf           │  0.95 raven_feather      │  1.25 slimeleaf_blue     ║
║    49 ghostwood          │     1 feather            │  1.25 slimeleaf_orange   ║
║    50 feather            │     1 ghostwood          │  1.25 slimeleaf_purple   ║
║    50 raven_feather      │     1 steeleaf           │   1.5 leaf               ║
║    61 stymph_feather     │   1.1 stymph_feather     │  1.56 titanium           ║
║    64 titanium           │   1.2 titanium           │  1.65 stymph_feather     ║
╟──────────────────────────┼──────────────────────────┼──────────────────────────╢
║ Total Power              │ Accuracy                 │ Modifier                 ║
╚══════════════════════════╧══════════════════════════╧══════════════════════════╝


Stat Tweaks
╔══════════════════════════╤═══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╤══════════════════════════╗
║ Total Power              │ HeadDurability            │ MiningSpeed              │ AttackDamage             │ HarvestLevel             │ HandleModifier           │ HandleDurability         │ ExtraDurability          │ DrawSpeed                │ Range                    │ BonusDamage              ║
║                          │ sqrt(abs(n*10))*sign(n)/3 │ (n+1)**2                 │ (n+1)**2/5               │ n*5                      │ (n+3)**2-9               │ log(abs(n)+1)*sign(n)+8  │ log(n+50)*2-4            │ sqrt(n*10)               │ n*4                      │ n*2                      ║
╟──────────────────────────┼───────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────╢
║    21 paper              │  -255 rubber              │  0.01 heavy              │     0 sponge             │     0 aquamarine         │     0 nagascale          │ -1400 energetic_alloy    │   -40 heavy              │     0 apatite            │     0 apatite            │    -4 meat_metal         ║
║    30 stone              │     9 paper               │  0.38 paper              │  0.04 paper              │     0 bone               │   0.1 alpha_fur          │  -350 ardite             │     0 endorium           │     0 knightmetal        │     0 knightmetal        │    -4 signalum           ║
║    41 construction_alloy │    17 universal_metal     │  0.38 xu_demonic_metal   │  0.08 ma.prosperity      │     0 cactus             │   0.1 paper              │  -350 firewood           │     0 nagascale          │     0 xu_enchanted_metal │     0 xu_enchanted_metal │    -2 paper              ║
║    42 wood               │    26 wood                │  0.62 ma.prosperity      │  0.75 construction_alloy │     0 chocolate          │  0.15 chocolate          │  -350 magmaslime         │     0 wolframium         │     0 xu_evil_metal      │     0 xu_evil_metal      │    -1 amber              ║
║    47 chocolate          │    26 xu_magical_wood     │  0.75 plague_metal       │  0.75 soularium          │     0 flint              │  0.25 xu_demonic_metal   │  -262 netherrack         │     1 alumite            │  0.01 heavy              │   0.1 heavy              │    -1 endstone           ║
║    49 flint              │    27 ma.prosperity       │  0.75 soularium          │     1 alpha_fur          │     0 ghostwood          │   0.4 dragonsteel_fire   │  -262 prismarine         │     1 psigem             │  0.08 chocolate          │   0.3 alpha_fur          │    -1 flint              ║
║    53 rubber             │    38 construction_alloy  │  0.94 construction_alloy │  1.35 blueslime          │     0 paper              │   0.4 dragonsteel_ice    │  -175 obsidian           │     1 psimetal           │   0.1 soularium          │   0.3 chocolate          │    -1 netherrack         ║
║    57 xu_magical_wood    │    38 electrum            │  1.13 dragonbone         │  1.35 slime              │     0 polyethylene       │   0.5 construction_alloy │  -105 flint              │     5 magnesium          │   0.2 amber              │   0.4 amber              │    -1 obsidian           ║
║    58 alpha_fur          │    48 fusewood            │   1.5 chocolate          │   1.5 cheese             │     0 stone              │   0.5 heavy              │   -87 blueslime          │     5 primal_metal       │   0.2 endstone           │   0.4 endstone           │    -1 prismarine         ║
║    61 ma.prosperity      │    60 heavy               │   1.5 stone              │   1.5 chocolate          │     0 wood               │   0.5 knightslime        │   -87 lead               │     5 void_crystal       │   0.2 flint              │   0.4 flint              │    -1 stone              ║
║    62 cactus             │    60 xu_demonic_metal    │   1.5 wood               │   1.5 rubber             │     1 alpha_fur          │   0.5 manyullyn          │   -87 stone              │     6 chocolate          │   0.2 netherrack         │   0.4 netherrack         │    -1 tanzanite          ║
║    66 netherrack         │    72 ghostwood           │   1.5 xu_magical_wood    │   1.5 wood               │     1 aluminium          │   0.5 polyethylene       │   -87 vibrant_alloy      │     8 construction_alloy │   0.2 obsidian           │   0.4 obsidian           │  -0.5 cheese             ║
║    67 certus_quartz      │    90 stone               │  1.58 magmaslime         │   1.5 xu_magical_wood    │     1 apatite            │   0.5 rubber             │   -75 meat_metal         │     8 thorium            │   0.2 prismarine         │   0.4 paper              │     0 apatite            ║
║    71 bone               │   100 certus_quartz       │  1.88 energetic_alloy    │  1.69 electrical_steel   │     1 blueslime          │   0.5 soularium          │   -52 malachite_gem      │     8 uranium            │   0.2 stone              │   0.4 prismarine         │     0 aquamarine         ║
║    73 dragonbone         │   100 treatedwood         │     2 alpha_fur          │  1.88 bone               │     1 cheese             │   0.5 stone              │   -52 peridot            │    10 black_quartz       │   0.2 tanzanite          │   0.4 stone              │     0 black_quartz       ║
║    75 aquamarine         │   104 obsidian            │  2.25 malachite_gem      │  1.88 conductive_iron    │     1 construction_alloy │   0.5 vibrant_alloy      │   -50 spectre            │    11 paper              │  0.25 neutronium         │   0.4 tanzanite          │     0 blueslime          ║
║    75 blueslime          │   110 dreamwood           │  2.25 tanzanite          │  1.88 psigem             │     1 copper             │   0.6 alumite            │   -44 electrum           │    11 wood               │  0.25 pulsating_iron     │   0.5 construction_alloy │     0 bone               ║
║    75 tanzanite          │   113 dragonbone          │  2.27 sponge             │  1.88 psimetal           │     1 darkwood           │   0.6 flint              │   -25 pink_slime         │    11 xu_magical_wood    │   0.3 dark_steel         │   0.5 meat_metal         │     0 cactus             ║
║    77 apatite            │   113 flint               │  2.42 endstone           │     2 pink_slime         │     1 livingrock         │   0.6 fluxed_electrum    │   -17 plague_metal       │    15 ma.prosperity      │   0.3 end_steel          │   0.5 rubber             │     0 certus_quartz      ║
║    77 endstone           │   113 sky_stone           │  2.63 ardite             │  2.17 flint              │     1 nagascale          │   0.6 prismarine         │   -10 heavy              │    15 malachite_gem      │  0.38 boron_nitride      │   0.5 soularium          │     0 construction_alloy ║
║    80 prismarine         │   118 magnesium           │  2.63 psigem             │  2.25 certus_quartz      │     1 rubber             │  0.63 ma.inferium        │     0 dreamwood          │    15 peridot            │  0.38 osmiridium         │   0.6 polyethylene       │     0 essence_metal      ║
║    81 polyethylene       │   120 livingwood          │  2.63 psimetal           │  2.25 copper             │     1 slime              │   0.7 desert_myrmex      │     0 emerald_plustic    │    15 ruby               │  0.38 thorium            │  0.63 ma.prosperity      │     0 firewood           ║
║    81 slime              │   131 aquamarine          │  2.63 vibrant_alloy      │  2.25 dragonbone         │     1 sponge             │   0.7 fierymetal         │     0 endstone           │    15 signalum           │   0.4 knightslime        │   0.7 desert_myrmex      │     0 flux_crystal       ║
║    81 sponge             │   135 steeleaf            │     3 cactus             │  2.25 electrum           │     1 tin                │   0.7 jungle_myrmex      │     0 nagascale          │    15 stone              │   0.4 lead               │   0.7 essence_metal      │     0 gelid_gem          ║
║    81 tin                │   135 thorium             │     3 certus_quartz      │  2.25 netherrack         │     2 carbon_fiber       │   0.7 lead               │     0 palis_crystal      │    15 treatedwood        │   0.4 osmium             │   0.7 jungle_myrmex      │     0 ghostwood          ║
║    82 livingrock         │   145 uranium             │     3 cheese             │  2.25 stone              │     2 certus_quartz      │   0.7 signalum           │     0 primal_metal       │    15 xu_demonic_metal   │   0.4 steel              │  0.75 mica               │     0 knightmetal        ║
║    82 treatedwood        │   150 bone                │     3 desert_myrmex      │  2.42 endstone           │     2 desert_myrmex      │   0.7 slime              │     0 ruby               │    18 boron              │   0.4 terrasteel         │  0.75 sponge             │     0 livingrock         ║
║    85 magmaslime         │   150 signalum            │     3 dreamwood          │   2.5 meat_metal         │     2 essence_metal      │   0.7 tanzanite          │     0 signalum           │    19 steel              │   0.4 topaz              │   0.8 ardite             │     0 livingwood         ║
║    88 cheese             │   150 tin                 │     3 jungle_myrmex      │  2.63 bronze             │     2 firewood           │  0.75 bloodwood          │     0 slime              │    19 tanzanite          │   0.4 uranium            │   0.8 energetic_alloy    │     0 mica               ║
║    88 copper             │   153 iron                │     3 peridot            │  2.63 lead               │     2 fluix              │  0.75 boron_nitride      │     0 tanzanite          │    20 livingwood         │  0.43 boron              │   0.8 platinum           │     0 palis_crystal      ║
║    89 firewood           │   158 cactus              │  3.02 blueslime          │  2.63 magnesium          │     2 fusewood           │  0.75 certus_quartz      │     0 titanium           │    20 lumium             │  0.45 ardite             │   0.8 redstone_alloy     │     0 pink_slime         ║
║    90 amber              │   158 copper              │  3.18 slime              │  2.63 xu_enchanted_metal │     2 jungle_myrmex      │  0.75 electrical_steel   │     0 universal_metal    │    20 restonia_crystal   │  0.48 osgloglas          │   0.8 restonia_crystal   │     0 polyethylene       ║
║    90 malachite_gem      │   160 conductive_iron     │  3.38 netherrack         │   2.7 ardite             │     2 plague_metal       │  0.75 nickel             │     0 void_crystal       │    20 tin                │   0.5 desert_myrmex      │   0.8 silver             │     0 redstone_alloy     ║
║    91 soularium          │   165 vibrant_alloy       │  3.45 amber              │     3 aquamarine         │     2 sentient_metal     │  0.75 restonia_crystal   │     0 void_metal         │    23 tough              │   0.5 energetic_alloy    │   0.8 void_metal         │     0 restonia_crystal   ║
║    92 plague_metal       │   170 livingrock          │  3.45 ruby               │     3 iron               │     2 treatedwood        │  0.75 sentient_metal     │     0 xu_evil_metal      │    25 aquamarine         │   0.5 hard_carbon        │  0.85 pink_slime         │     0 rubber             ║
║    93 lead               │   180 palis_crystal       │  3.75 flint              │     3 polyethylene       │     2 wolframium         │  0.75 thorium            │     1 livingwood         │    25 certus_quartz      │   0.5 invar              │   0.9 cactus             │     0 slime              ║
║    96 peridot            │   180 restonia_crystal    │  3.75 livingwood         │     3 pulsating_iron     │     3 advanced_alloy     │  0.78 ma.prudentium      │     1 osgloglas          │    25 sky_stone          │   0.5 iron               │   0.9 electrical_steel   │     0 soularium          ║
║    97 silver             │   183 ma.base_essence     │  3.75 sapphire           │     3 treatedwood        │     3 amber              │   0.8 apatite            │     1 pigiron            │    30 dreamwood          │   0.5 jungle_myrmex      │   0.9 livingrock         │     0 sponge             ║
║    98 wolframium         │   188 silver              │  3.75 silver             │     3 uranium            │     3 bloodwood          │   0.8 aquamarine         │     1 psigem             │    30 flint              │   0.5 ma.base_essence    │  0.99 ma.inferium        │     0 tin                ║
║    98 xu_demonic_metal   │   203 netherrack          │  3.75 weezer             │  3.08 cobalt             │     3 bronze             │   0.8 black_quartz       │     1 psimetal           │    30 fluix              │   0.5 magnesium          │     1 aquamarine         │     0 treatedwood        ║
║    99 livingwood         │   203 starmetal           │  3.82 bone               │  3.09 alumite            │     3 dragonbone         │   0.8 energetic_metal    │     1 redstone_alloy     │    30 ghostwood          │   0.5 manasteel          │     1 black_quartz       │     0 universal_metal    ║
║   100 obsidian           │   220 polyethylene        │  3.83 alumite            │  3.15 obsidian           │     3 endorium           │   0.8 iridium            │     4 paper              │    30 titanium           │   0.5 meat_metal         │     1 blueslime          │     0 void_crystal       ║
║   103 ruby               │   225 aluminium           │  3.93 osmiridium         │  3.25 ma.base_essence    │     3 fierymetal         │   0.8 lumium             │     5 lumium             │    32 endstone           │   0.5 sky_stone          │     1 carbon_fiber       │     0 wolframium         ║
║   105 void_crystal       │   230 electrical_steel    │  3.94 lead               │  3.38 pigiron            │     3 fluix_steel        │   0.8 ma.soulium         │     6 chocolate          │    35 aluminium          │   0.5 starmetal          │     1 certus_quartz      │     0 wood               ║
║   106 dreamwood          │   233 psigem              │  3.98 copper             │  3.38 redstone_alloy     │     3 iron               │   0.8 mica               │     6 ma.prosperity      │    35 apatite            │   0.5 wolframium         │     1 crystal_matrix     │     0 xu_enchanted_metal ║
║   106 iron               │   233 psimetal            │     4 apatite            │  3.38 thorium            │     3 lonsdaleite        │   0.8 osmium             │     8 construction_alloy │    35 hard_carbon        │  0.55 bronze             │     1 electrum           │     0 xu_evil_metal      ║
║   106 palis_crystal      │   250 lumium              │     4 pink_slime         │  3.45 ma.soulium         │     3 malachite_gem      │   0.8 platinum           │    10 apatite            │    35 livingrock         │  0.55 tough              │     1 emerald_plustic    │     0 xu_magical_wood    ║
║   106 psigem             │   255 void_crystal        │     4 treatedwood        │   3.5 dreamwood          │     3 netherrack         │   0.8 refined_glowstone  │    10 aquamarine         │    38 cactus             │  0.58 ma.inferium        │     1 energetic_metal    │   0.8 ma.prosperity      ║
║   106 psimetal           │   259 ma.inferium         │  4.13 endorium           │  3.55 cactus             │     3 peridot            │   0.8 steeleaf           │    10 constantan         │    38 iron               │   0.6 bound_metal        │     1 firewood           │   0.9 emerald_plustic    ║
║   107 ardite             │   263 xu_enchanted_metal  │  4.13 prismarine         │  3.75 silver             │     3 prismarine         │   0.8 tin                │    10 livingrock         │    38 ma.base_essence    │   0.6 copper             │     1 flux_crystal       │     1 alpha_fur          ║
║   108 essence_metal      │   270 manasteel           │  4.13 wolframium         │  3.83 knightslime        │     3 ruby               │   0.8 topaz              │    10 restonia_crystal   │    38 manyullyn          │   0.6 dragonbone         │     1 infinity_metal     │     1 aluminium          ║
║   111 sapphire           │   270 redstone_alloy      │   4.2 spectre            │     4 aluminium          │     3 sapphire           │   0.8 uranium            │    10 sky_stone          │    40 constantan         │   0.6 iridium            │     1 livingwood         │     1 ardite             ║
║   112 desert_myrmex      │   275 constantan          │  4.25 meat_metal         │     4 livingrock         │     3 tanzanite          │   0.8 void_crystal       │    10 tin                │    40 manasteel          │   0.6 livingrock         │     1 pink_metal         │     1 dreamwood          ║
║   112 jungle_myrmex      │   275 fluix               │  4.35 knightslime        │     4 mica               │     3 topaz              │  0.85 boron              │    15 cactus             │    40 polyethylene       │   0.6 pigiron            │     1 primal_metal       │     1 electrical_steel   ║
║   112 vibrant_alloy      │   275 mica                │   4.5 amethyst           │     4 sky_stone          │     3 xu_magical_wood    │  0.85 cactus             │    15 fluix              │    45 sentient_metal     │  0.65 alumite            │     1 signalum           │     1 magmaslime         ║
║   115 sky_stone          │   300 alpha_fur           │   4.5 firewood           │     4 tin                │     4 black_quartz       │  0.85 endstone           │    15 ghostwood          │    45 vibrant_alloy      │  0.65 amethyst           │     1 spectre            │   1.5 carbon_fiber       ║
║   116 ma.base_essence    │   300 desert_myrmex       │   4.5 iron               │  4.13 firewood           │     4 bound_metal        │  0.85 iron               │    15 xu_enchanted_metal │    47 ma.soulium         │  0.65 ma.soulium         │     1 vibrant_alloy      │   1.5 lonsdaleite        ║
║   117 ma.soulium         │   300 jungle_myrmex       │   4.5 livingrock         │   4.2 energetic_alloy    │     4 dark_steel         │  0.85 magmaslime         │    19 wood               │    49 bone               │  0.65 manyullyn          │     1 wolframium         │   1.5 pladium            ║
║   118 xu_enchanted_metal │   300 nickel              │   4.5 tin                │   4.2 restonia_crystal   │     4 electrum           │  0.85 netherrack         │    19 xu_magical_wood    │    49 topaz              │  0.65 nickel             │     1 wood               │   1.5 plague_metal       ║
║   119 bronze             │   300 refined_glowstone   │   4.5 topaz              │  4.28 amber              │     4 emerald_plustic    │   0.9 aluminium          │    20 black_quartz       │    50 draconium          │  0.65 refined_obsidian   │     1 xu_magical_wood    │   1.5 sentient_metal     ║
║   120 alumite            │   300 sentient_metal      │   4.5 void_crystal       │   4.5 apatite            │     4 enori_crystal      │   0.9 cobalt             │    20 essence_metal      │    50 energetic_metal    │  0.67 spectre            │  1.05 magmaslime         │  1.91 ma.inferium        ║
║   120 topaz              │   315 endstone            │  4.65 pigiron            │   4.5 constantan         │     4 flux_crystal       │   0.9 dark_steel         │    20 invar              │    50 essence_metal      │   0.7 enori_crystal      │   1.1 aluminium          │     2 advanced_alloy     ║
║   121 fluix              │   319 chocolate           │  4.67 aquamarine         │   4.5 fluix              │     4 lead               │   0.9 end_steel          │    23 amber              │    50 invar              │   0.7 fluix_steel        │   1.1 draconium          │     2 chocolate          ║
║   122 mica               │   320 enori_crystal       │  4.76 ma.soulium         │   4.5 signalum           │     4 livingwood         │   0.9 fluix_steel        │    23 copper             │    50 rubber             │   0.7 thaumium           │   1.1 dreamwood          │     2 crystal_matrix     ║
║   123 pink_slime         │   323 bronze              │   4.8 palis_crystal      │   4.5 steel              │     4 ma.base_essence    │   0.9 flux_crystal       │    23 osmiridium         │    50 xu_evil_metal      │   0.7 xu_demonic_metal   │   1.1 gelid_gem          │     2 desert_myrmex      ║
║   124 electrical_steel   │   323 prismarine          │  4.88 electrical_steel   │   4.5 steeleaf           │     4 ma.prosperity      │   0.9 livingrock         │    25 aluminium          │    53 emerald_plustic    │  0.73 ma.prudentium      │   1.1 palis_crystal      │     2 enori_crystal      ║
║   124 spectre            │   326 lead                │  4.99 ma.base_essence    │   4.5 titanium           │     4 ma.soulium         │   0.9 manasteel          │    25 mica               │    55 enori_crystal      │  0.75 aquamarine         │   1.1 sunnarium          │     2 fluxed_electrum    ║
║   125 ma.inferium        │   342 pigiron             │     5 essence_metal      │   4.5 topaz              │     4 manasteel          │   0.9 obsidian           │    25 polyethylene       │    55 refined_glowstone  │  0.75 cobalt             │   1.1 xu_demonic_metal   │     2 jungle_myrmex      ║
║   126 meat_metal         │   345 nagascale           │     5 mica               │  4.58 malachite_gem      │     4 palis_crystal      │   0.9 steel              │    30 certus_quartz      │    56 electrical_steel   │  0.75 constantan         │  1.13 treatedwood        │     2 knightslime        ║
║   127 knightslime        │   350 bloodwood           │     5 polyethylene       │  4.58 peridot            │     4 restonia_crystal   │  0.95 silver             │    30 cheese             │    56 ma.inferium        │  0.75 elementium         │  1.15 bone               │     2 lumium             ║
║   128 nagascale          │   375 apatite             │     5 rubber             │  4.62 osmiridium         │     4 silver             │  0.97 ma.intermedium     │    30 diamantine_crystal │    56 netherrack         │  0.75 enderium           │  1.15 lumium             │     2 nagascale          ║
║   128 pigiron            │   384 wolframium          │     5 sky_stone          │  4.65 prismarine         │     4 void_crystal       │     1 advanced_alloy     │    30 lonsdaleite        │    60 bloodwood          │  0.75 energetic_metal    │   1.2 bloodwood          │     2 nickel             ║
║   129 emerald_plustic    │   394 alumite             │   5.1 bronze             │   4.8 ruby               │     4 weezer             │     1 amber              │    30 mirion             │    60 bronze             │  0.75 palis_crystal      │   1.2 diamantine_crystal │     2 silver             ║
║   131 endorium           │   400 essence_metal       │  5.25 dark_steel         │   4.8 sapphire           │     5 dark_matter        │     1 bound_metal        │    30 refined_glowstone  │    60 diamantine_crystal │  0.75 red_matter         │   1.2 dragonbone         │     2 sky_stone          ║
║   132 steeleaf           │   400 spectre             │  5.25 dragonsteel_fire   │  4.88 wolframium         │     5 diamantine_crystal │     1 dark_matter        │    30 sentient_metal     │    60 nickel             │  0.75 sentient_metal     │   1.2 lonsdaleite        │  2.32 ma.prudentium      ║
║   133 uranium            │   400 thaumium            │  5.25 dragonsteel_ice    │     5 black_quartz       │     5 draconium          │     1 elementium         │    31 thaumium           │    60 osgloglas          │  0.75 vibrant_alloy      │   1.2 manyullyn          │   2.5 bloodwood          ║
║   135 black_quartz       │   405 steel               │  5.25 emerald_plustic    │     5 bloodwood          │     5 emeraldic_crystal  │     1 enori_crystal      │    35 nickel             │    60 xu_enchanted_metal │   0.8 bloodwood          │   1.2 weezer             │   2.5 conductive_iron    ║
║   135 energetic_alloy    │   413 dark_steel          │  5.25 knightmetal        │     5 elementium         │     5 end_steel          │     1 firewood           │    37 magnesium          │    64 spectre            │   0.8 fluxed_electrum    │  1.25 advanced_alloy     │   2.5 draconium          ║
║   139 constantan         │   413 firewood            │  5.25 steel              │     5 essence_metal      │     5 endstone           │     1 fluix              │    38 bone               │    68 obsidian           │  0.85 advanced_alloy     │  1.25 constantan         │   2.5 spectre            ║
║   139 manasteel          │   425 invar               │  5.25 steeleaf           │     5 manasteel          │     5 heavy              │     1 hard_carbon        │    38 end_steel          │    68 steeleaf           │  0.85 dark_matter        │  1.25 elementium         │     3 cobalt             ║
║   141 bloodwood          │   448 darkwood            │  5.25 xu_enchanted_metal │     5 refined_glowstone  │     5 invar              │     1 infinity_metal     │    38 ma.inferium        │    70 sunnarium          │  0.85 draconic_metal     │  1.25 fluix              │     3 constantan         ║
║   143 carbon_fiber       │   450 end_steel           │  5.27 ma.inferium        │  5.25 emerald_plustic    │     5 ma.inferium        │     1 magnesium          │    38 silver             │    75 amber              │  0.85 emeraldic_crystal  │  1.25 fluxed_electrum    │     3 ionite             ║
║   143 fierymetal         │   450 fluix_steel         │  5.27 manyullyn          │  5.25 livingwood         │     5 magmaslime         │     1 neutronium         │    40 bloodwood          │    75 amethyst           │  0.85 slime              │  1.25 refined_glowstone  │     3 kyronite           ║
║   143 steel              │   450 magmaslime          │   5.3 obsidian           │  5.25 magmaslime         │     5 osmium             │     1 primal_metal       │    40 bound_metal        │    75 copper             │  0.85 titanium           │  1.25 sentient_metal     │     3 lead               ║
║   144 redstone_alloy     │   466 ma.soulium          │   5.4 fierymetal         │  5.25 tanzanite          │     5 pigiron            │     1 red_matter         │    40 energetic_metal    │    75 dragonbone         │   0.9 dragonsteel_fire   │  1.25 sky_stone          │   3.1 ma.soulium         ║
║   146 fluix_steel        │   470 bound_metal         │  5.63 osgloglas          │   5.4 palis_crystal      │     5 pink_slime         │     1 sapphire           │    40 flux_crystal       │    75 emeraldic_crystal  │   0.9 dragonsteel_ice    │  1.25 tin                │   3.5 energetic_metal    ║
║   147 dark_steel         │   480 black_quartz        │  5.63 redstone_alloy     │   5.5 carbon_fiber       │     5 redstone_alloy     │     1 sky_stone          │    40 sunnarium          │    75 fluix_steel        │   0.9 fluix              │  1.25 universal_metal    │   3.5 magnesium          ║
║   148 nickel             │   480 malachite_gem       │  5.63 uranium            │   5.5 fluix_steel        │     5 soularium          │     1 terrasteel         │    41 ma.soulium         │    75 lead               │   0.9 lonsdaleite        │   1.3 cobalt             │  3.52 ma.base_essence    ║
║   149 knightmetal        │   480 peridot             │     6 boron              │   5.5 invar              │     5 steel              │     1 thaumium           │    42 thorium            │    75 litherite          │   0.9 nagascale          │   1.3 emeraldic_crystal  │     4 bound_metal        ║
║   149 sentient_metal     │   488 tanzanite           │     6 carbon_fiber       │   5.5 lumium             │     5 thaumium           │     1 wood               │    45 iron               │    75 lonsdaleite        │   0.9 tin                │   1.3 fluix_steel        │     4 dark_matter        ║
║   149 weezer             │   492 boron               │     6 constantan         │   5.5 nickel             │     6 alumite            │     1 xu_evil_metal      │    45 uranium            │    75 ma.prudentium      │   0.9 wyvern_metal       │   1.3 lead               │     4 darkwood           ║
║   152 amethyst           │   495 ruby                │     6 elementium         │   5.5 osmium             │     6 amethyst           │     1 xu_magical_wood    │    49 dragonbone         │    75 prismarine         │  0.95 bone               │   1.3 slime              │     4 diamantine_crystal ║
║   154 manyullyn          │   500 flux_crystal        │     6 fluix              │   5.5 thaumium           │     6 constantan         │  1.05 copper             │    49 ma.base_essence    │    80 alpha_fur          │  0.95 draconium          │   1.3 titanium           │     4 dragonbone         ║
║   154 thorium            │   500 osmium              │     6 manasteel          │  5.63 hard_carbon        │     6 energetic_metal    │  1.05 pulsating_iron     │    50 draconium          │    80 bound_metal        │     1 alpha_fur          │   1.3 wyvern_metal       │     4 electrum           ║
║   155 flux_crystal       │   500 xu_evil_metal       │  6.01 ma.prudentium      │     6 amethyst           │     6 knightmetal        │   1.1 bronze             │    50 emeraldic_crystal  │    80 elementium         │     1 aluminium          │  1.34 ma.prudentium      │     4 energetic_alloy    ║
║   156 lonsdaleite        │   512 draconium           │   6.5 black_quartz       │     6 diamantine_crystal │     6 knightslime        │   1.1 constantan         │    50 manasteel          │    80 flux_crystal       │     1 diamantine_crystal │  1.35 enori_crystal      │     4 fluix              ║
║   158 invar              │   512 energetic_metal     │   6.5 fluix_steel        │     6 endorium           │     6 lumium             │   1.1 draconium          │    50 refined_obsidian   │    90 sapphire           │     1 firewood           │  1.35 fierymetal         │     4 gelid_enderium     ║
║   162 osmiridium         │   518 energetic_alloy     │   6.5 invar              │     6 energetic_metal    │     6 ma.prudentium      │   1.1 dragonbone         │    53 alumite            │    94 knightslime        │     1 lumium             │  1.35 refined_obsidian   │     4 malachite_gem      ║
║   163 electrum           │   518 ma.prudentium       │   6.5 nickel             │     6 lonsdaleite        │     6 meat_metal         │   1.1 dreamwood          │    53 bronze             │    95 carbon_fiber       │     1 platinum           │   1.4 bound_metal        │     4 manyullyn          ║
║   163 ma.prudentium      │   518 topaz               │  6.68 nagascale          │     6 spectre            │     6 mica               │   1.1 electrum           │    53 topaz              │    95 void_metal         │     1 psigem             │   1.4 malachite_gem      │     4 peridot            ║
║   165 advanced_alloy     │   525 sapphire            │  6.75 thorium            │     6 void_crystal       │     6 nickel             │   1.1 emerald_plustic    │    56 ma.prudentium      │   100 platinum           │     1 psimetal           │   1.4 peridot            │     4 pink_metal         ║
║   165 boron              │   540 fierymetal          │     7 advanced_alloy     │  6.48 dark_steel         │     6 obsidian           │   1.1 palis_crystal      │    60 electrical_steel   │   110 fusewood           │     1 refined_glowstone  │   1.4 pigiron            │     4 psigem             ║
║   166 draconium          │   548 amber               │     7 bloodwood          │   6.5 platinum           │     6 pink_metal         │   1.1 plague_metal       │    60 fluix_steel        │   110 thaumium           │     1 sapphire           │   1.4 ruby               │     4 psimetal           ║
║   172 thaumium           │   580 sunnarium           │     7 draconium          │  6.54 manyullyn          │     6 refined_glowstone  │   1.1 tough              │    60 fusewood           │   113 cheese             │     1 treatedwood        │   1.4 topaz              │     4 refined_glowstone  ║
║   173 heavy              │   585 blueslime           │     7 flux_crystal       │  6.65 starmetal          │     6 signalum           │   1.1 xu_enchanted_metal │    60 litherite          │   113 desert_myrmex      │     1 wood               │  1.44 osgloglas          │     4 ruby               ║
║   176 osmium             │   585 cobalt              │     7 lonsdaleite        │  6.75 boron              │     6 sky_stone          │  1.12 ma.superium        │    60 starmetal          │   113 end_steel          │     1 xu_magical_wood    │  1.45 copper             │     4 sapphire           ║
║   179 aluminium          │   585 plague_metal        │     7 sentient_metal     │  6.75 ma.inferium        │     6 starmetal          │  1.16 osmiridium         │    70 carbon_fiber       │   113 firewood           │  1.05 blueslime          │   1.5 boron_nitride      │     4 steeleaf           ║
║   180 magnesium          │   615 manyullyn           │     7 thaumium           │  6.75 vibrant_alloy      │     6 steeleaf           │   1.2 bone               │    70 enori_crystal      │   113 jungle_myrmex      │  1.05 cactus             │   1.5 bronze             │     4 sunnarium          ║
║   181 ghostwood          │   625 cheese              │   7.5 diamantine_crystal │     7 emeraldic_crystal  │     6 titanium           │   1.2 lonsdaleite        │    75 amethyst           │   113 ma.intermedium     │  1.05 void_metal         │   1.5 dark_matter        │     4 uranium            ║
║   182 diamantine_crystal │   638 knightslime         │   7.5 osmium             │     7 fluxed_electrum    │     7 ardite             │   1.2 osgloglas          │    75 cobalt             │   113 magmaslime         │  1.07 ma.intermedium     │   1.5 enderium           │     4 xu_demonic_metal   ║
║   186 elementium         │   666 infinity_metal      │   7.5 tough              │  7.23 nagascale          │     7 cobalt             │   1.2 ruby               │    75 knightmetal        │   113 silver             │   1.1 dreamwood          │   1.5 gelid_enderium     │  4.02 ma.intermedium     ║
║   187 lumium             │   675 knightmetal         │     8 bound_metal        │   7.5 end_steel          │     7 energetic_alloy    │   1.2 sponge             │    75 ma.intermedium     │   120 boron_nitride      │   1.1 emerald_plustic    │   1.5 iron               │   4.5 boron              ║
║   190 energetic_metal    │   680 void_metal          │     8 emeraldic_crystal  │   7.5 enori_crystal      │     7 hard_carbon        │  1.25 diamantine_crystal │    75 rubber             │   120 fluxed_electrum    │   1.1 magmaslime         │   1.5 ma.base_essence    │   4.5 erodium            ║
║   190 enori_crystal      │   690 pulsating_iron      │     8 enderium           │   7.5 ghostwood          │     7 litherite          │  1.25 emeraldic_crystal  │    75 sapphire           │   120 terrasteel         │   1.1 pink_metal         │   1.5 ma.soulium         │   4.5 thorium            ║
║   191 bound_metal        │   700 elementium          │     8 fluxed_electrum    │   7.5 plague_metal       │     7 ma.intermedium     │  1.25 enderium           │    75 steeleaf           │   135 erodium            │  1.15 certus_quartz      │   1.5 manasteel          │     5 copper             ║
║   193 osgloglas          │   743 ardite              │     8 refined_obsidian   │   7.5 refined_obsidian   │     7 psigem             │  1.25 invar              │    75 weezer             │   135 plague_metal       │  1.15 sponge             │   1.5 nickel             │     5 endorium           ║
║   199 tough              │   747 hard_carbon         │     8 terrasteel         │   7.5 terrasteel         │     7 psimetal           │  1.25 knightmetal        │    75 xu_demonic_metal   │   150 blueslime          │   1.2 black_quartz       │   1.5 sapphire           │     5 hard_carbon        ║
║   201 emeraldic_crystal  │   750 slime               │  8.25 hard_carbon        │   7.5 tough              │     7 pulsating_iron     │  1.25 refined_obsidian   │    90 fluxed_electrum    │   150 fierymetal         │   1.2 chaotic_metal      │   1.5 starmetal          │     5 tough              ║
║   203 fluxed_electrum    │   768 endorium            │  8.25 magnesium          │   7.5 weezer             │     7 spectre            │  1.25 sunnarium          │    91 treatedwood        │   154 pigiron            │   1.2 endorium           │   1.5 thorium            │     5 vibrant_alloy      ║
║   204 cobalt             │   788 sponge              │  8.31 ma.intermedium     │  7.95 fierymetal         │     7 sunnarium          │  1.25 treatedwood        │   100 alpha_fur          │   168 mirion             │   1.2 flux_crystal       │   1.6 alumite            │     5 void_metal         ║
║   204 hard_carbon        │   800 advanced_alloy      │   8.5 energetic_metal    │     8 draconium          │     7 tough              │   1.3 blueslime          │   100 elementium         │   169 ma.superium        │   1.2 livingwood         │   1.6 draconic_metal     │   5.5 boron_nitride      ║
║   214 starmetal          │   800 fluxed_electrum     │  8.65 starmetal          │     8 flux_crystal       │     7 uranium            │   1.3 carbon_fiber       │   102 boron              │   175 osmium             │   1.2 silver             │   1.6 psigem             │   5.5 iridium            ║
║   215 refined_glowstone  │   825 amethyst            │     9 boron_nitride      │  8.25 advanced_alloy     │     7 xu_demonic_metal   │   1.3 malachite_gem      │   105 erodium            │   180 darkwood           │  1.21 ma.superium        │   1.6 psimetal           │  5.94 ma.superium        ║
║   221 refined_obsidian   │   836 tough               │     9 cobalt             │  8.25 boron_nitride      │     7 xu_enchanted_metal │   1.3 peridot            │   113 dark_steel         │   180 enderium           │  1.25 universal_metal    │   1.6 uranium            │     6 aethium            ║
║   222 xu_evil_metal      │   840 lonsdaleite         │     9 electrum           │  8.25 osgloglas          │     8 boron              │   1.3 psigem             │   113 steel              │   188 dark_steel         │  1.25 void_crystal       │  1.63 ma.intermedium     │     6 bronze             ║
║   225 pulsating_iron     │   875 soularium           │     9 enori_crystal      │   8.5 iridium            │     8 conductive_iron    │   1.3 psimetal           │   120 darkwood           │   188 electrum           │   1.3 pink_slime         │   1.7 amethyst           │     6 emeraldic_crystal  ║
║   237 conductive_iron    │   900 litherite           │     9 ghostwood          │   8.5 pink_metal         │     8 electrical_steel   │  1.35 ma.supremium       │   120 platinum           │   188 pulsating_iron     │  1.33 ma.supremium       │   1.7 boron              │     6 fierymetal         ║
║   242 platinum           │   917 emerald_plustic     │     9 iridium            │  8.99 xu_demonic_metal   │     8 erodium            │   1.4 ardite             │   124 ma.superium        │   188 sponge             │  1.35 mirion             │  1.75 invar              │     6 fluix_steel        ║
║   243 ma.intermedium     │   935 meat_metal          │     9 lumium             │     9 enderium           │     8 ma.superium        │   1.4 endorium           │   125 chaotic_metal      │   195 kyronite           │   1.4 ma.prosperity      │  1.75 osmium             │     6 invar              ║
║   245 fusewood           │   960 diamantine_crystal  │     9 platinum           │     9 fusewood           │     8 magnesium          │   1.4 ma.base_essence    │   125 crystal_matrix     │   200 wyvern_metal       │   1.4 malachite_gem      │  1.75 terrasteel         │     6 litherite          ║
║   245 titanium           │   970 primal_metal        │     9 pulsating_iron     │     9 void_metal         │     8 manyullyn          │   1.4 ma.prosperity      │   125 pink_metal         │   210 palis_crystal      │   1.4 peridot            │   1.8 conductive_iron    │     6 osmium             ║
║   246 enderium           │   975 erodium             │  9.49 titanium           │   9.5 crystal_matrix     │     8 mirion             │   1.4 spectre            │   144 boron_nitride      │   225 advanced_alloy     │   1.5 cheese             │   1.8 thaumium           │     6 wyvern_metal       ║
║   247 terrasteel         │   975 osmiridium          │  9.75 xu_evil_metal      │   9.5 knightmetal        │     8 osmiridium         │   1.4 wolframium         │   150 conductive_iron    │   225 cobalt             │   1.5 conductive_iron    │   1.8 void_crystal       │   6.5 amethyst           ║
║   249 boron_nitride      │  1035 ma.intermedium      │    10 aluminium          │  9.75 xu_evil_metal      │     8 refined_obsidian   │  1.44 pigiron            │   150 enderium           │   225 ma.supremium       │   1.5 crystal_matrix     │  1.91 ma.superium        │  6.56 osgloglas          ║
║   262 iridium            │  1050 kyronite            │    10 refined_glowstone  │  9.93 ma.prudentium      │     8 thorium            │   1.5 amethyst           │   150 kyronite           │   250 pink_metal         │   1.5 electrical_steel   │     2 chaotic_metal      │   6.6 titanium           ║
║   265 signalum           │  1100 refined_obsidian    │ 10.13 conductive_iron    │    10 sentient_metal     │     8 xu_evil_metal      │   1.5 cheese             │   150 ma.supremium       │   255 pladium            │   1.5 electrum           │     2 cheese             │     7 alumite            ║
║   271 end_steel          │  1125 dragonsteel_fire    │    11 fusewood           │    10 universal_metal    │     9 boron_nitride      │   1.5 crystal_matrix     │   150 osmium             │   263 slime              │   1.5 essence_metal      │     2 endorium           │     7 elementium         ║
║   292 restonia_crystal   │  1125 dragonsteel_ice     │ 11.32 end_steel          │  10.5 bound_metal        │     9 dragonsteel_fire   │   1.5 essence_metal      │   160 iridium            │   270 gelid_gem          │   1.5 fierymetal         │     2 hard_carbon        │     7 enderium           ║
║   306 sunnarium          │  1125 pladium             │    12 sunnarium          │  10.5 primal_metal       │     9 dragonsteel_ice    │   1.5 gelid_enderium     │   174 tough              │   300 draconic_metal     │   1.5 fusewood           │     2 iridium            │     7 iron               ║
║   311 void_metal         │  1125 weezer              │    12 void_metal         │    12 litherite          │     9 dreamwood          │   1.5 pink_metal         │   175 advanced_alloy     │   300 energetic_alloy    │   1.5 gelid_enderium     │     2 knightslime        │     7 manasteel          ║
║   322 pink_metal         │  1130 emeraldic_crystal   │    12 wyvern_metal       │    12 sunnarium          │     9 fluxed_electrum    │   1.5 starmetal          │   180 gelid_gem          │   300 pink_slime         │   1.5 paper              │     2 magnesium          │     7 pigiron            ║
║   335 dragonsteel_fire   │  1200 carbon_fiber        │  12.4 ma.superium        │ 12.13 desert_myrmex      │     9 kyronite           │   1.5 weezer             │   180 terrasteel         │   300 refined_obsidian   │   1.5 primal_metal       │     2 red_matter         │     7 refined_obsidian   ║
║   335 dragonsteel_ice    │  1200 ionite              │  12.5 pink_metal         │ 12.13 jungle_myrmex      │     9 osgloglas          │   1.5 wyvern_metal       │   188 manyullyn          │   315 ionite             │   1.5 restonia_crystal   │     2 steel              │     7 topaz              ║
║   377 crystal_matrix     │  1200 pink_slime          │    13 crystal_matrix     │ 13.84 ma.intermedium     │     9 platinum           │   1.6 mirion             │   188 pulsating_iron     │   338 ardite             │   1.5 ruby               │  2.05 osmiridium         │  7.32 ma.supremium       ║
║   380 primal_metal       │  1275 aethium             │    13 neutronium         │    14 dark_matter        │     9 vibrant_alloy      │  1.75 draconic_metal     │   188 sponge             │   339 redstone_alloy     │   1.5 weezer             │   2.2 tough              │     8 fusewood           ║
║   380 universal_metal    │  1400 platinum            │    13 signalum           │    14 darkwood           │    10 enderium           │   1.8 void_metal         │   195 pladium            │   340 chaotic_metal      │   1.6 carbon_fiber       │  2.25 steeleaf           │     8 platinum           ║
║   381 wyvern_metal       │  1420 titanium            │  13.5 mirion             │    15 erodium            │    10 iridium            │  1.95 pink_slime         │   225 desert_myrmex      │   340 iridium            │  1.75 mica               │  2.35 ma.supremium       │     8 pulsating_iron     ║
║   386 ma.superium        │  1439 mirion              │  13.5 primal_metal       │    15 wyvern_metal       │    10 ma.supremium       │     2 fusewood           │   225 jungle_myrmex      │   350 gelid_enderium     │  1.75 polyethylene       │   2.5 dark_steel         │     8 weezer             ║
║   432 dark_matter        │  1650 terrasteel          │    14 restonia_crystal   │    16 neutronium         │    10 pladium            │     2 gelid_gem          │   233 hard_carbon        │   375 aethium            │   1.8 steeleaf           │   2.5 end_steel          │     9 dark_steel         ║
║   447 darkwood           │  1680 osgloglas           │    15 dark_matter        │ 17.43 ma.superium        │    10 red_matter         │     2 livingwood         │   240 ionite             │   375 weezer             │     2 plague_metal       │   2.5 fusewood           │     9 steel              ║
║   464 mirion             │  1700 enderium            │    15 universal_metal    │    18 kyronite           │    10 void_metal         │     2 universal_metal    │   250 wyvern_metal       │   376 conductive_iron    │     2 rubber             │     3 aethium            │     9 terrasteel         ║
║   514 neutronium         │  1736 boron_nitride       │    16 darkwood           │    20 heavy              │    11 crystal_matrix     │   2.2 chaotic_metal      │   280 gelid_enderium     │   383 dragonsteel_fire   │     2 sunnarium          │     3 dragonsteel_fire   │   9.5 thaumium           ║
║   597 litherite          │  1789 pink_metal          │ 16.69 ma.supremium       │ 20.25 mirion             │    11 elementium         │   2.5 conductive_iron    │   285 aethium            │   383 dragonsteel_ice    │  2.25 litherite          │     3 dragonsteel_ice    │    10 draconic_metal     ║
║   599 ma.supremium       │  1800 gelid_gem           │    18 draconic_metal     │    21 pladium            │    11 ionite             │   2.7 ghostwood          │   300 draconic_metal     │   400 crystal_matrix     │  2.55 erodium            │     3 ghostwood          │    10 osmiridium         ║
║   642 gelid_gem          │  1900 iridium             │    18 gelid_gem          │    22 gelid_enderium     │    11 terrasteel         │   2.8 titanium           │   300 dragonsteel_fire   │   401 meat_metal         │  2.85 kyronite           │     3 nagascale          │    10 red_matter         ║
║   683 erodium            │  2070 ma.superium         │  19.5 litherite          │ 22.55 ma.supremium       │    11 universal_metal    │   2.9 meat_metal         │   300 dragonsteel_ice    │   420 universal_metal    │     3 construction_alloy │     3 plague_metal       │ 10.98 end_steel          ║
║   718 gelid_enderium     │  2140 wyvern_metal        │    20 gelid_enderium     │    23 red_matter         │    12 aethium            │     3 aethium            │   300 fierymetal         │   497 starmetal          │     3 gelid_gem          │  3.15 ionite             │    12 primal_metal       ║
║   758 red_matter         │  2800 gelid_enderium      │    20 red_matter         │    24 gelid_gem          │    12 neutronium         │     3 erodium            │   320 dark_matter        │   540 dark_matter        │  3.15 pladium            │   3.3 pladium            │    12 starmetal          ║
║   776 kyronite           │  3200 crystal_matrix      │    21 erodium            │    24 ionite             │    12 primal_metal       │     3 ionite             │   384 wolframium         │   600 knightmetal        │  3.45 ionite             │  3.45 kyronite           │    14 dragonsteel_fire   ║
║   813 draconic_metal     │  3200 dark_matter         │    22 chaotic_metal      │ 26.25 dragonsteel_fire   │    12 wyvern_metal       │     3 kyronite           │   475 knightslime        │   600 osmiridium         │   3.6 darkwood           │   3.5 pulsating_iron     │    14 dragonsteel_ice    ║
║   877 pladium            │  3650 draconic_metal      │  22.5 kyronite           │ 26.25 dragonsteel_ice    │    13 draconic_metal     │     3 litherite          │   555 neutronium         │   666 infinity_metal     │  3.75 aethium            │   3.6 erodium            │  15.5 mirion             ║
║   992 ionite             │  4140 ma.supremium        │    24 pladium            │    27 aethium            │    13 gelid_enderium     │     3 pladium            │   666 infinity_metal     │   740 mica               │   4.5 ghostwood          │  3.75 litherite          │    18 chaotic_metal      ║
║  1117 aethium            │  6660 chaotic_metal       │    25 infinity_metal     │    35 draconic_metal     │    13 gelid_gem          │     3 redstone_alloy     │   720 red_matter         │   938 soularium          │     5 redstone_alloy     │     4 neutronium         │    20 heavy              ║
║  1616 chaotic_metal      │  7200 red_matter          │  25.5 ionite             │    64 chaotic_metal      │    14 chaotic_metal      │   3.6 darkwood           │   768 endorium           │  1111 neutronium         │     5 signalum           │   4.4 darkwood           │    20 neutronium         ║
║ 19541 infinity_metal     │ 11111 neutronium          │    27 aethium            │   300 infinity_metal     │    15 infinity_metal     │     4 energetic_alloy    │  1125 soularium          │  1200 red_matter         │  6.66 infinity_metal     │   4.5 mirion             │   300 infinity_metal     ║
╟──────────────────────────┼───────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────┼──────────────────────────╢
║ Total Power              │ HeadDurability            │ MiningSpeed              │ AttackDamage             │ HarvestLevel             │ HandleModifier           │ HandleDurability         │ ExtraDurability          │ DrawSpeed                │ Range                    │ BonusDamage              ║
╚══════════════════════════╧═══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╧══════════════════════════╝


